### ISSUE TITLE
`[vim-hug-neovim-rpc] rpc method [nvim_set_client_info] not implemented in pythonx/neovim_rpc_methods.py. Please send PR or contact the mantainer.`

### ISSUE THREAD

**Issue by ujihisa** [Shougo/deoplete.nvim#1039]
* Shougo is already on it
* There's a workaround for that: `pip3 install --user pynvim==0.3.2`
* This error is not because of deoplete but because of pynvim's breaking changes.

**Comment by Shougo** [comment]
Please test https://github.com/roxma/vim-hug-neovim-rpc/pull/63.

**Comment by ujihisa** [comment]
confirmed that latest version everything is good!

**Comment by Jeansen** [comment]
The commit message to f64b1b471839d59ba9d4a333112f5f46ea28ed31 says: Don't use vim.vars.get(): it does not work in Vim8. Now the question is, is it fixed (but still does not work in Vim 8) Or should it be fixed because it does not work in Vim 8? So far, I am still having this issue when using editing any file:
```
[deoplete] Traceback (most recent call last):
  File "/home/marcel/.vim//plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 107, in _add_source
    source = Source(self._vim)
  File "/home/marcel/.vim//plugged/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 35, in __init__
    'deople
te#sources#ternjs#filetypes', []))
  File "/home/marcel/.local/lib/python3.7/site-packages/pynvim/api/common.py", line 138, in get
    return self.__getitem__(key)
  File "/home/marcel/.local/lib/python3.7/site-packages/pynvim/api/common.py", line 110, in __getitem__
    raise transform_keyerror(exc)
  File "/hom
e/marcel/.local/lib/python3.7/site-packages/pynvim/api/common.py", line 108, in __getitem__
    return self._get(key)
  File "/home/marcel/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/marcel/.local/lib/python3.7/si
te-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: 'deoplete#sources#ternjs#filetypes'
Could not load source: /home/marcel/.vim//plugged/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py.  Use :messages / see above for error detai
ls.
```

**Comment by Jeansen** [comment]
Fixed by: https://github.com/carlitux/deoplete-ternjs/commit/ca0ee77276bc688f847b566d64b32e4bb62691d8

**Comment by Shougo** [comment]
Yes.  It is the source problem.
