### ISSUE TITLE
Error when loading source go: 'deoplete#sources#go#auto_goos'.

### ISSUE THREAD

**Issue by kodango** [Shougo/deoplete.nvim#1046]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

I've installed both deoplete and deoplete-go plugin, but when open the .go file to type any chars, the error messages shows:

```
[deoplete] Traceback (most recent call last):
  File "/Users/kodango/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 448, in _itersource
    source.on_init(context)
  File "/Users/kodango/.vim/plugged/deoplete-go/rplugin/python3/deoplete/sources/deoplete_go.py", line 51, in on_init
    vars.get('deoplete#sources#go#auto_goos', False)
  File "/Users/kodango/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 138, in get
    return self.__getitem__(key)
  File "/Users/kodango/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 110, in __getitem__
    raise transform_keyerror(exc)
  File "/Users/kodango/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 108, in __getitem__
    return self._get(key)
  File "/Users/kodango/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/kodango/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: 'deoplete#sources#go#auto_goos'
Error when loading source go: 'deoplete#sources#go#auto_goos'. Ignoring..  Use :messages / see above for error details.
```

## Expected

No error found

## Environment Information

 * deoplete version (SHA1):

 * OS:

 * neovim/Vim `:version` output:

```
$ vim --version | head -10
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  9 2019 11:20:52)
macOS version
Included patches: 1-2102
Compiled by Homebrew
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
    Plug 'Shougo/deoplete.nvim'
    Plug 'deoplete-plugins/deoplete-go', { 'do': 'make'}

    let g:deoplete#enable_at_startup = 1
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
    let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
```

**Comment by Shougo** [comment]
It is not deoplete's error.
Please read this.

https://github.com/deoplete-plugins/deoplete-jedi/issues/237

**Comment by Shougo** [comment]
It is fixed in the latest version of deoplete-go.
