### ISSUE TITLE
Error in child: NvimError('Invalid buffer id'). が出た

### ISSUE THREAD

**Issue by octaltree** [Shougo/deoplete.nvim#1089]
# Problems summary
日本語で失礼します。最新コミット(a76d2fbfdc)でもなるが、再現できない。
コミット(d21aef18a12)で編集中のバッファに入力し即座に`<esc>q:aw<enter>`したときにinvalid buffer idというエラーを吐いた。
```
[deoplete] Traceback (most recent call last):
  File "/home/octaltree/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/autoload/deoplete
/_main.py", line 56, in main
    child.main_loop(stdout)
  File "/home/octaltree/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/d
eoplete/child.py", line 72, in main_loop
    ret = self.main(name, args, queue_id)
  File "/home/octaltree/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/d
eoplete/child.py", line 91, in main
    results = self._merge_results(args[0], queue_id)
  File "/home/octaltree/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/d
eoplete/child.py", line 161, in _merge_results
    results = self._gather_results(context)
  File "/home/octaltree/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/d
eoplete/child.py", line 188, in _gather_results
    self._vim.current.buffer.vars.get('changedtick', 0)):
  File "/usr/lib/python3.8/site-packages/pynvim/api/common.py", line 138, in get
    return self.__getitem__(key)
  File "/usr/lib/python3.8/site-packages/pynvim/api/common.py", line 110, in __getitem__
    raise transform_keyerror(exc)
  File "/usr/lib/python3.8/site-packages/pynvim/api/common.py", line 108, in __getitem__
    return self._get(key)
  File "/usr/lib/python3.8/site-packages/pynvim/api/common.py", line 58, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Invalid buffer id
Error in child: NvimError('Invalid buffer id').  Use :messages / see above for error details.
[deoplete] The child process is exited!
```

最新コミット(a76d2fbfdc)はバッファ入力後に補完候補が出るのがとても早いので、
そのために再現しなくなったと勝手に思ってる。

## Expected
ローカル環境で編集後保存するたびにエラー出て1ヶ月以上困っていた。

## Environment Information

 * deoplete version (SHA1): d21aef18a1297e4a1a2a451ed03c515b4af0fd81
 * OS: Linux version 5.4.27-1-MANJARO (builduser@development) (gcc version 9.3.0 (Arch Linux 9.3.0-1)) #1 SMP PREEMPT Sat Mar 21 16:33:27 UTC 2020

 * neovim/Vim `:version` output:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_L
EVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wco
nversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics
-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UN
IBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/inc
lude -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='rxvt'

## tmux
  - OK: escape-time: 1ms
  - INFO: $TERM: tmux-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. 'termguicolors'          won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: g:python_host_prog is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set g:python_host_prog to avoid surprises.
  - INFO: Executable: /usr/bin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python version: 2.7.17
  - INFO: pynvim version: 0.3.2 (outdated; from /usr/lib/python2.7/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Python 3 provider (optional)
  - INFO: g:python3_host_prog is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set g:python3_host_prog to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.2
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
  - INFO: Host: /home/octaltree/.gem/ruby/2.4.0/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v13.11.0
  - INFO: Neovim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.8.0

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

再現するにも(補完が遅い？)補完ソースが必要だった。minimal init.vim
```vim
set runtimepath+=~/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim
set runtimepath+=~/.config/nvim/dein/repos/github.com/Shougo/neco-syntax
set runtimepath+=~/.config/nvim/dein/repos/github.com/Shougo/neco-vim
set runtimepath+=~/.config/nvim/dein/repos/github.com/sheerun/vim-polyglot
let g:deoplete#enable_at_startup = 1

nnoremap ; q:a
nnoremap : ;
nnoremap q; :
vnoremap ; q:a
vnoremap : ;

set completeopt+=noselect
set completeopt-=preview
let g:deoplete#auto_complete_delay = 0
let g:deoplete#auto_complete_start_length = 1
call deoplete#custom#option('refresh_always', v:true)

inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS>  deoplete#smart_close_popup()."\<C-h>"
imap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function() abort
  return deoplete#close_popup() . "\<CR>"
endfunction

call deoplete#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. NVIM_PYTHON_LOG_FILE=/tmp/log NVIM_PYTHON_LOG_LEVEL=DEBUG nvim -u init.vim foo.sh
2. echoと打ち込み即座に`<esc>;w<enter>` 100%出るわけではないので素早く打つのを繰り返す

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

[/tmp/log/log_py3_rplugin](https://github.com/Shougo/deoplete.nvim/files/4379978/log_py3_rplugin.txt)

## Upload the log file

![log](https://user-images.githubusercontent.com/7942952/77523520-341cb580-6ec9-11ea-89cf-bc6cc15282ad.gif)

**Comment by Shougo** [comment]
OK.  I have fixed the error.
