### ISSUE TITLE
disabled_syntaxes does not appear to work

### ISSUE THREAD

**Issue by YorickPeterse** [Shougo/deoplete.nvim#1123]
# Problems summary

When setting the `disabled_syntaxes` option, I expected completion to not take place in these syntax groups. For example, when adding the `String` syntax group I expect that deoplete does not complete inside a string. But instead deoplete _does_ complete. Take for example this setting:

```
call deoplete#custom#source('_', 'disabled_syntaxes', ['Comment', 'String'])
```

Despite Comment and String being in the list, deoplete will continue to provide completion suggestions in these syntax groups. Is this intentional and am I simply misunderstanding the purpose of this option, or is this a bug?

## Expected

No completion suggestions are provided in the disabled syntax groups.

## Environment Information

 * deoplete version (SHA1): ba3913cc52b457877836f7423b0929b770dda42b

 * OS: Arch Linux, `Linux roach 5.8.2-arch1-1 #1 SMP PREEMPT Thu, 20 Aug 2020 20:45:00 +0000 x86_64 GNU/Linux`

 * neovim/Vim `:version` output:

<details>
<summary>version output</summary>

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

</details>

 * `:checkhealth` or `:CheckHealth` result(neovim only):

<details>
<summary>CheckHealth output</summary>

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release
    LuaJIT

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6003'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/bin/python2"
  - INFO: Executable: /usr/bin/python2
  - ERROR: Command error (job=11, exit code 1): `'/usr/bin/python2' -c 'import sys; sys.path.remove(""); import neovim; print(neovim.__file__)'` (in '/home/yorickpeterse/Projects/general/dotfiles/dotfiles/.config/nvim/plugged/deoplete.nvim')
    Output: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
    Stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
  - INFO: Python version: 2.7.18
  - INFO: pynvim version: unable to load neovim Python module
  - ERROR: pynvim is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: pip install pynvim

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python"
  - INFO: Executable: /usr/bin/python
  - INFO: Python version: 3.8.5
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.8.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

</details>

NOTE: I'm not using Python 2, hence the pynvim errors.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let g:plug_url_format = 'git@github.com:%s.git'

call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

set completeopt=menu

filetype plugin indent on
syntax on

call deoplete#custom#source('_', 'disabled_syntaxes', ['Comment', 'String'])

let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

Create `/tmp/test.vim` and provide it with the `init.vim` contents above. This example assumes vim-plug is installed.

Next, create `/tmp/test.py` like so:

```python
def foo():
    return 10

"bar"
"f"
```

Then, start (Neo)Vim like so:

```
nvim -u /tmp/test.vim /tmp/test.py
```

Move the cursor so it's placed after the `f` on the last line, like so:

```
"f|"
  ^ cursor here
```

Then press "o". A completion menu will now show up like so:

![Screenshot from 2020-08-24 23-26-40](https://user-images.githubusercontent.com/86065/91098168-48740280-e661-11ea-930c-853edbc5dfba.png)

I did not expect this, given `String` is in the `disabled_syntaxes` group.

## Generate a logfile if appropriate

[log.txt](https://github.com/Shougo/deoplete.nvim/files/5120342/log.txt)

**Comment by YorickPeterse** [comment]
Note that in this example I used Python, but this issue appears to affect any language; not just Python.

**Comment by Shougo** [comment]
```vim
call deoplete#custom#source('_', 'disabled_syntaxes', ['Comment', 'String', 'Constant'])
```

Because `pythonString` -> `String` -> `Constant`.
You can check it by `:highlight pythonString`.

`Constant` is detected on deoplete.

**Comment by YorickPeterse** [comment]
@Shougo I think the `Constant` addition is not necessary. For example, in my case `String` is not linked to `Constant`.

Setting that aside, commit 7ab4c1bde7f9bd8824219594b07e4c1aa0814d4e fixes the problem so thanks a lot!
