### ISSUE TITLE
No module named 'vim'

### ISSUE THREAD

**Issue by d9d6ka** [Shougo/deoplete.nvim#1130]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Deoplete doesn't start with no 'vim' package error. The package is installed as `pip freeze` claims.
neovim, python are installed via scoop.
Here is the output of `:UpdateRemotePlugins`
```
Encountered ModuleNotFoundError loading plugin at C:/Users/vadim/AppData/Local/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete: No module named 'vim'
Traceback (most recent call last):
  File "C:\Users\vadim\scoop\apps\python\current\lib\site-packages\pynvim\plugin\host.py", line 171, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "C:\Users\vadim\scoop\apps\python\current\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "C:\Users\vadim\scoop\apps\python\current\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
ModuleNotFoundError: No module named 'vim'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: C:\Users\vadim\AppData\Local\nvim-data/rplugin.vim
```

## Environment Information

 * deoplete version (SHA1): latest from master branch (commit 895fafe)

 * OS: Win10 Home, version 2004

 * neovim/Vim `:version` output:
```
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Скомпилирован  appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

            общесистемный файл vimrc: "$VIM\sysinit.vim"
          значение $VIM по умолчанию: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log{PID}
    - and then create an issue on github
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if has('win32') || has('win64')
    let g:python3_host_prog="C:/Users/vadim/scoop/apps/python/current/python.exe"
endif

silent! call plug#begin()
    if has('nvim')
        Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    else
        Plug 'Shougo/deoplete.nvim'
        Plug 'roxma/nvim-yarp'
        Plug 'roxma/vim-hug-neovim-rpc'
    endif
call plug#end()

let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Install vim-plug
 2. Install deoplete
 3. :UpdateRemotePlugins

**Comment by Shougo** [comment]
`nvim-yarp` is loaded in neovim.  Please don't load it in neovim.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/__init__.py#L14

Please see the code.

**Comment by d9d6ka** [comment]
Thanks!
