### ISSUE TITLE
No module named vim on UpdateRemotePlugins in nvim

### ISSUE THREAD

**Issue by rcorre** [Shougo/deoplete.nvim#1174]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Running `:UpdateRemotePlugins` in `nvim` prints:
```
Encountered ModuleNotFoundError loading plugin at /home/rcorre/dotfiles/home/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete: No module named 'vim'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.9/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.9/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
ModuleNotFoundError: No module named 'vim'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/rcorre/.local/share/nvim/rplugin.vim
```

I've tried explicitly setting `g:python3_host_prog=/usr/bin/python3`, and leaving it unset.
`:pythonx import vim` succeeds.

## Expected

`UpdateRemotePlugins` succeeds.

## Environment Information

 * deoplete version (SHA1): 77edc521a5c56c8480ec3ee74fca9954167b1b14

 * OS: ArchLinux

 * neovim/Vim `:version` output:

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

Run :checkhealth for more info
 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /home/rcorre/.asdf/shims/python2 does not have the "neovim" module. :help |provider-python|
          /home/rcorre/.asdf/shims/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /home/rcorre/.asdf/shims/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /home/rcorre/.asdf/shims/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.3
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v10.19.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. run `nvim -u init.nvim` with above init.nvim file
 2. run `:UpdateRemotePlugins`

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file
[logs.zip](https://github.com/Shougo/deoplete.nvim/files/6384275/logs.zip)

**Comment by Shougo** [comment]
Please don't install/enable `nvim-yarp` in neovim enviroment.
yarp is loaded.  Why?  I think your minimal vimrc is broken.

It must be reproduce-able  for other people.  We have not ESP skills.

**Comment by Shougo** [comment]
Note: `vim` module is loaded when `yarp` is loaded only
https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/__init__.py#L15

But your minimal env does not have yarp.

```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

let g:deoplete#enable_at_startup = 1
```

**Comment by Shougo** [comment]
You should use the real minimal vimrc without plugin manager.

```vim
set rtp+=~/work/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

It should work.

**Comment by rcorre** [comment]
Hi @Shougo , thanks for the response! I get the same error with your suggested vimrc.

**Comment by Shougo** [comment]
Please test the latest version.

**Comment by rcorre** [comment]
That gives a new error:

```
Encountered AttributeError loading plugin at /home/rcorre/dotfiles/home/.config/nvim/plugged/deoplete.nvim/rplugin
/python3/deoplete: module 'pynvim' has no attribute 'call'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pynvim/plugin/host.py", line 165, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.9/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.9/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
AttributeError: module 'pynvim' has no attribute 'call'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/rcorre/.local/share/nvim/rplugin.vim
```

That might be that I just tried installing nvim 0.5 though, let me try 0.4 again ...

**Comment by rcorre** [comment]
Nope, same with 0.4

**Comment by Shougo** [comment]
Really???  Why I cannot reproduce the problem?

**Comment by Shougo** [comment]
Please test the latest version.

**Comment by rcorre** [comment]
Same :(

**Comment by Shougo** [comment]
Really?  Oh no.  I cannot fix it.
This is open source.  Pull request is wellcome.

**Comment by Shougo** [comment]
Gave up

**Comment by rcorre** [comment]
no worries, thank you for taking a look!

**Comment by Shougo** [comment]
You can test it in other environment and docker.
I cannot fix it without reproduce.

**Comment by Shougo** [comment]
Your `pynvim` module seems broken.  You should reinstall it.

**Comment by Shougo** [comment]
> INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.

It seems danger.

**Comment by Shougo** [comment]
> Encountered AttributeError loading plugin at /home/rcorre/dotfiles/home/.config/nvim/plugged/deoplete.nvim/rplugin
/python3/deoplete: module 'pynvim' has no attribute 'call'

Why it load `call` attribute?
It is not included the source code.

**Comment by Shougo** [comment]
>Hi @Shougo , thanks for the response! I get the same error with your suggested vimrc.

https://github.com/Shougo/deoplete.nvim/issues/1174#issuecomment-827604616

Why the path is not same with my vimrc?  Please explain it.

**Comment by rcorre** [comment]
`.config` is a symlink into `~/dotfiles`. That could be an issue. Let me experiment

**Comment by Shougo** [comment]
Oh...

**Comment by rcorre** [comment]
So I've tried setting `host_prog` as well as cloning deoplete directly into `/tmp` and pointing init.nvim at that:

```
let g:python3_host_prog = '/usr/bin/python3'
set rtp+=/tmp/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```

No symlinks, and checkhealth doesn't report multiple python anymore:

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.9.4
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github
```

I still get the same error though :(

Don't worry about continuing to debug unless you're curious.
I suspect something is wrong with my environment, so I can keep trying to figure that out.

**Comment by Shougo** [comment]
Please test the clean environment. Docker is better though.
Unfortunately, neovim-python sometimes broken.  You can see it from issues.

**Comment by Shougo** [comment]
I will replace deoplete to ddc.vim in the future to throw away neovim-python problems.

https://github.com/Shougo/ddc.vim
