### ISSUE TITLE
Errors with python 3.10

### ISSUE THREAD

**Issue by petobens** [Shougo/deoplete.nvim#1194]
```
[deoplete] Traceback (most recent call last):
  File "/home/pedro/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/child.py", line 112, in _add_source
    Source = import_plugin(path, 'source', 'Source')
  File "/home/pedro/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/util.py", line 67, in import_plugin
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/docker.py", line 13, in <module>
    from dockerhub.dockerhub import DockerHub
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/dockerhub/dockerhub/dockerhub.py", line 10, in <module>
    import urllib3
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/urllib3/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import (
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/urllib3/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/urllib3/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/urllib3/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/urllib3/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/urllib3/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/urllib3/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
Could not load source: /home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/docker.py  Use :messages / see above for error details.
```
When using deoplete with python 3.10 I get the error above.

**Comment by Shougo** [comment]
It is not deoplete error.  Please read the stacktrace.

```
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/docker.py", line 13, in <module>
    from dockerhub.dockerhub import DockerHub
  File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/dockerhub/dockerhub/dockerhub.py", line 10, in <module>
    import urllib3
```

https://github.com/deoplete-plugins/deoplete-docker

**Comment by Shougo** [comment]
https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections

**Comment by Shougo** [comment]
I have updated deoplete-docker.

**Comment by petobens** [comment]
Thanks!!
