### ISSUE TITLE
ValueError: `column` parameter (8) is not in a valid range (0-0) for line 421 ('\n').

### ISSUE THREAD

**Issue by Griiid** [Shougo/deoplete.nvim#1200]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

The error message shows when I typing a variable:

```
[deoplete] Traceback (most recent call last):
  File "/Users/eddiehsu/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 203, in _gather_results
    result = self._get_result(context, source)
  File "/Users/eddiehsu/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 267, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/Users/eddiehsu/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/eddiehsu/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 202, in gather_candidates
    completions = self.get_completions(script, line, col)
  File "/Users/eddiehsu/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/profiler.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/eddiehsu/.vim/plugged/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 148, in get_completions
    return script.complete(line, col)
  File "/Users/eddiehsu/.pyenv/versions/3.8.13/lib/python3.8/site-packages/jedi/api/helpers.py", line 484, in wrapper
    raise ValueError('`column` parameter (%d) is not in a valid range '
ValueError: `column` parameter (8) is not in a valid range (0-0) for line 421 ('\n').
Error from jedi: `column` parameter (8) is not in a valid range (0-0) for line 421 ('\n').  Use :messages / see above for error details.
```

## Expected
No error.

## Environment Information

 * deoplete version (SHA1):  
6.2
I don't know how to get SHA1, the version 6.2 is from `:help deoplete-options`, I can provide it if you can tell me how to get it.

 * OS:
macOS Monterey 12.5.1（21G83）

 * neovim/Vim `:version` output:
v0.7.0

 * `:checkhealth` or `:CheckHealth` result(neovim only):  
```
coc: health#coc#check
========================================================================
  - OK: nvim version satisfied
  - OK: Environment check passed
  - OK: Javascript bundle build/index.js found
  - OK: Service started

deoplete: health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github

jedi: health#jedi#check
========================================================================
## jedi

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 3 provider (optional)
  - INFO: pyenv: Path: /usr/local/Cellar/pyenv/2.3.3/libexec/pyenv
  - INFO: pyenv: Root: /Users/eddiehsu/.pyenv
  - INFO: Using: g:python3_host_prog = "/Users/eddiehsu/.pyenv/versions/3.8.13/bin/python3"
  - INFO: Executable: /Users/eddiehsu/.pyenv/versions/3.8.13/bin/python3
  - INFO: Python version: 3.8.13
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - WARNING: $VIRTUAL_ENV is set to: /Users/eddiehsu/.pyenv/versions/3.8.13/envs/BotFat-GCR-Async_venv
    And its /bin directory contains: python, python3, python3.8
    But $PATH yields this python executable: /Users/eddiehsu/.pyenv/versions/BotFat-GCR-Async_venv/bin/python
    And $PATH in subshells yields this python executable: /Users/eddiehsu/.pyenv/versions/BotFat-GCR-Async_venv/bin/python
    And $PATH yields this python3 executable: /Users/eddiehsu/.pyenv/versions/BotFat-GCR-Async_venv/bin/python3
    And $PATH in subshells yields this python3 executable: /Users/eddiehsu/.pyenv/versions/BotFat-GCR-Async_venv/bin/python3
    And $PATH yields this python3.8 executable: /Users/eddiehsu/.pyenv/versions/BotFat-GCR-Async_venv/bin/python3.8
    And $PATH in subshells yields this python3.8 executable: /Users/eddiehsu/.pyenv/versions/BotFat-GCR-Async_venv/bin/python3.8
    So invoking Python may lead to unexpected results.
    - ADVICE:
      - $PATH ambiguities arise if the virtualenv is not properly activated prior to launching Nvim. Close Nvim, activate the virtualenv, check that invoking Python from the command line launches the correct one, then relaunch Nvim.
      - $PATH ambiguities in subshells typically are caused by your shell config overriding the $PATH previously set by the virtualenv. Either prevent them from doing so, or use this workaround: https://vi.stackexchange.com/a/34996

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v16.17.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

targets: health#targets#check
========================================================================
  - OK: No conflicting mappings found

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/eddiehsu/.cache/nvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath=&runtimepath
call plug#begin('~/.vim/plugged')
Plug 'davidhalter/jedi-vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'deoplete-plugins/deoplete-jedi'
call plug#end()
let g:jedi#use_tabs_not_buffers=1
let g:jedi#goto_stubs_command=""
let g:jedi#completions_enabled = 0
let g:deoplete#enable_at_startup = 1
let py_global_version = readfile('/Users/' . $USER . '/.pyenv/version')[0]
let g:python3_host_prog = '/Users/' . $USER . '/.pyenv/versions/' . py_global_version . '/bin/python3'
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open a file in my project.
2. Type d
![截圖 2022-11-15 11 38 46](https://user-images.githubusercontent.com/82018290/201822176-b3cbf1ed-9b66-428d-8143-784aacc98921.png)
3. Type f
![截圖 2022-11-15 11 38 52](https://user-images.githubusercontent.com/82018290/201822199-993b4d46-7cec-4570-9d3a-ff0033323ae9.png)

## Screenshot (if possible)

The screenshot pictures are in the reproduce-section

## Upload the log file

The error is at around line 4368.

[log_py3_rplugin.log](https://github.com/Shougo/deoplete.nvim/files/10009087/log_py3_rplugin.log)

**Comment by Shougo** [comment]
It seems jedi's error instead of deoplete.

**Comment by Shougo** [comment]
Please update `deoplete-jedi` to the latest.
