### ISSUE TITLE
Deoplete Error messages with vim-javacomplete2

### ISSUE THREAD

**Issue by SageEx** [Shougo/deoplete.nvim#158]
Everything was working well when suddenly deoplete reprted that an error has occured.
Is this a deoplete issue or javacomplete2 issue ? 
```
match 1 of 69
match 1 of 69
match 1 of 35
match 1 of 35
match 1 of 97
match 1 of 97
match 24 of 97
match 30 of 97
match 1 of 97
match 1 of 97
match 31 of 97
match 35 of 97
match 37 of 97
match 56 of 97
match 89 of 97
match 93 of 97
match 95 of 97
match 1 of 3
match 1 of 3
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/arindam/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 5
5, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/home/arindam/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 9
0, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/home/arindam/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 1
58, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/home/arindam/.config/nvim/plugged/vim-javacomplete2/rplugin/python3/deoplete/sources/javacomp
lete2.py", line 17, in gather_candidates
[deoplete]     return self.vim.call('javacomplete#complete#complete#Complete', 0, '')
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 132, in call
[deoplete]     return self._session.request('vim_call_function', name, args, **kwargs)
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/api/common.py", line 230, in request
[deoplete]     return walk(self._in, self._session.request(name, *args, **kwargs),
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 90, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(let):E745: Using a List as a Number'
[deoplete] An error has occurred. Please execute :messages command.
```

**Comment by Shougo** [comment]
It is javacomplete2 source problem.

https://github.com/artur-shaik/vim-javacomplete2/blob/master/rplugin/python3/deoplete/sources/javacomplete2.py

`javacomplete#complete#complete#Complete()` seems return Number instead of List.
Cannot fix.

**Comment by SageEx** [comment]
Thanks.
