### ISSUE TITLE
TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by ranranking** [Shougo/deoplete.nvim#179]
When editing some of of my files, this error shows up:

    [deoplete] Traceback (most recent call last):
    [deoplete]   File "/Users/ranranking/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 57, in completion_begin
    [deoplete]     complete_position, candidates = self.gather_candidates(context)
    [deoplete]   File "/Users/ranranking/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 92, in gather_candidates
    [deoplete]     results = self.gather_results(context)
    [deoplete]   File "/Users/ranranking/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 164, in gather_results
    [deoplete]     context['candidates'] = source.gather_candidates(context)
    [deoplete]   File     "/Users/ranranking/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 61, in gather_candidates
    [deoplete]     new_candidates = parse_tags(f)
    [deoplete]   File "/Users/ranranking/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 73, in parse_tags

    [deoplete]     p.findall(x) for x in f.readlines()
    [deoplete] TypeError: reduce() of empty sequence with no initial value
    [deoplete] An error has occurred. Please execute :messages command.

**Comment by mattsawyer77** [comment]
I'm seeing this too, though usually with many more errors:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 55, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 90, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 59, in gather_candidates
[deoplete]     new_candidates = parse_tags(f)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 71, in parse_tags
[deoplete]     p.findall(x) for x in f.readlines()
[deoplete] TypeError: reduce() of empty sequence with no initial value
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 55, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 90, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 59, in gather_candidates
[deoplete]     new_candidates = parse_tags(f)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 71, in parse_tags
[deoplete]     p.findall(x) for x in f.readlines()
[deoplete] TypeError: reduce() of empty sequence with no initial value
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 55, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 90, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 59, in gather_candidates
[deoplete]     new_candidates = parse_tags(f)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 71, in parse_tags
[deoplete]     p.findall(x) for x in f.readlines()
[deoplete] TypeError: reduce() of empty sequence with no initial value
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 55, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 90, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 59, in gather_candidates
[deoplete]     new_candidates = parse_tags(f)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 71, in parse_tags
[deoplete]     p.findall(x) for x in f.readlines()
[deoplete] TypeError: reduce() of empty sequence with no initial value
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 55, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 90, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 59, in gather_candidates
[deoplete]     new_candidates = parse_tags(f)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 71, in parse_tags
[deoplete]     p.findall(x) for x in f.readlines()
[deoplete] TypeError: reduce() of empty sequence with no initial value
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 55, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 90, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 59, in gather_candidates
[deoplete]     new_candidates = parse_tags(f)
[deoplete]   File "/Users/sawyer/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 71, in parse_tags
[deoplete]     p.findall(x) for x in f.readlines()
[deoplete] TypeError: reduce() of empty sequence with no initial value
[deoplete] An error has occurred. Please execute :messages command.
```

**Comment by ranranking** [comment]
yeah, I just copied part of it. since it was the same error for multiple times.

**Comment by zchee** [comment]
@ranranking @mattsawyer77 Hi,

error logs are very important to debug, but another information is too few...
Could you post init.vim that can reproduce the problem?

Also, see https://github.com/Shougo/deoplete.nvim/blob/master/CONTRIBUTING.md

**Comment by mattsawyer77** [comment]
@Shougo thank you for fixing this!

**Comment by Shougo** [comment]
Fixed.

**Comment by ranranking** [comment]
thank you!

**Comment by CrashyBang** [comment]
Not entirely sure if this is the right place to ask about this but I seem to be getting this error when using this guide: https://gregjs.com/vim/2016/configuring-the-deoplete-asynchronous-keyword-completion-plugin-with-tern-for-vim/

The error flashes at the bottom of my editor so I can't really read it properly is there an error log I can check? To get you more info?

Basically I am trying to set up deoplete with tern:

Here is my init.vim: https://gist.github.com/CrashyBang/6a8ac0906de5e28a78a6624c4f5d34cd

Is there anything obvious that anyone can see???

Cheers.

**Comment by Shougo** [comment]
@CrashyBang Please upload `:messages` result.

**Comment by CrashyBang** [comment]
Hey @Shougo,

Here is the output (This is not all of it as it is just the same thing again and again).

```bash
[deoplete]     p.findall(x) for x in self.vim.buffers[bufnr]                                                                                                                                                                                  
[deoplete]   File "/home/otis/.local/lib/python3.4/site-packages/neovim/api/common.py", line 138, in __getitem__                                                                                                                              
[deoplete]     return self._fetch()[idx]                                                                                                                                                                                                      
[deoplete] IndexError: list index out of range                                                                                                                                                                                                
[deoplete] An error has occurred. Please execute :messages command.                                                                                                                                                                           
[deoplete] Traceback (most recent call last):                                                                                                                                                                                                 
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin                                                                                                                  
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                                                                                                                
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_candidates                                                                                                                 
[deoplete]     results = self.gather_results(context)                                                                                                                                                                                         
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results                                                                                                                   
[deoplete]     context['candidates'] = source.gather_candidates(context)                                                                                                                                                                      
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 24, in gather_candidates                                                                                                           
[deoplete]     self.__make_cache(context, self.vim.current.buffer.number)                                                                                                                                                                     
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 57, in __make_cache                                                                                                                
[deoplete]     p.findall(x) for x in self.vim.buffers[bufnr]                                                                                                                                                                                  
[deoplete]   File "/home/otis/.local/lib/python3.4/site-packages/neovim/api/common.py", line 138, in __getitem__                                                                                                                              
[deoplete]     return self._fetch()[idx]                                                                                                                                                                                                      
[deoplete] IndexError: list index out of range                                                                                                                                                                                                
[deoplete] An error has occurred. Please execute :messages command.                                                                                                                                                                           
[deoplete] Traceback (most recent call last):                                                                                                                                                                                                 
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin                                                                                                                  
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                                                                                                                
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_candidates                                                                                                                 
[deoplete]     results = self.gather_results(context)                                                                                                                                                                                         
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results                                                                                                                   
[deoplete]     context['candidates'] = source.gather_candidates(context)                                                                                                                                                                      
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 24, in gather_candidates                                                                                                           
[deoplete]     self.__make_cache(context, self.vim.current.buffer.number)                                                                                                                                                                     
[deoplete]   File "/home/otis/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 57, in __make_cache                                                                                                                
[deoplete]     p.findall(x) for x in self.vim.buffers[bufnr]                                                                                                                                                                                  
[deoplete]   File "/home/otis/.local/lib/python3.4/site-packages/neovim/api/common.py", line 138, in __getitem__                                                                                                                              
[deoplete]     return self._fetch()[idx]
```

**Comment by Shougo** [comment]
OK.  It is the same problem.

https://github.com/Shougo/deoplete.nvim/issues/253

Please update deoplete.

**Comment by CrashyBang** [comment]
Hey @Shougo,

That fixed it! Sorry I thought I was running the latest version sorry to bother you :L.

Cheers,
Otis.
