### ISSUE TITLE
Editing files with arbitrary binary characters causes Deoplete errors

### ISSUE THREAD

**Issue by rolandcrosby** [Shougo/deoplete.nvim#181]
# Problems summary
When editing a file with arbitrary sequences of bytes that are not valid UTF-8, Deoplete fails ungracefully and prints a bunch of errors to the messages list.

## Expected
Deoplete fails gracefully instead of triggering Unicode errors in Python.

## Environment Information

 * OS: Mac OS X 10.10.5
 * Neovim version: NVIM v0.1.0-42-g1ee6a6e

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
let g:python3_host_prog = expand('$HOME/.pyenv/versions/nvim/bin/python3')
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. launch nvim with minimal nvimrc above
 2. open a file with non-UTF8 byte sequences in binary mode: `:e ++bin ~/Desktop/deotest.txt` (this file just consists of a single byte, 0xfc)
 3. enter insert mode and start typing
 4. view errors by running `:messages`:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/Desktop/deotest.txt" [noeol] 1L, 1C
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/rcrosby/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 57, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/rcrosby/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 92, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/rcrosby/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 164, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/rcrosby/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 57, in gather_candidates
[deoplete]     p.findall(x) for x in self.vim.current.buffer
[deoplete]   File "/Users/rcrosby/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 57, in <listcomp>
[deoplete]     p.findall(x) for x in self.vim.current.buffer
[deoplete]   File "/Users/rcrosby/.pyenv/versions/nvim/lib/python3.5/site-packages/neovim/api/buffer.py", line 92, in __iter__
[deoplete]     lines = self[:]
[deoplete]   File "/Users/rcrosby/.pyenv/versions/nvim/lib/python3.5/site-packages/neovim/api/buffer.py", line 55, in __getitem__
[deoplete]     True, include_end)
[deoplete]   File "/Users/rcrosby/.pyenv/versions/nvim/lib/python3.5/site-packages/neovim/api/common.py", line 231, in request
[deoplete]     self, name, 'out-request')
[deoplete]   File "/Users/rcrosby/.pyenv/versions/nvim/lib/python3.5/site-packages/neovim/api/common.py", line 254, in walk
[deoplete]     return list(walk(fn, o, *args) for o in obj)
[deoplete]   File "/Users/rcrosby/.pyenv/versions/nvim/lib/python3.5/site-packages/neovim/api/common.py", line 254, in <genexpr>
[deoplete]     return list(walk(fn, o, *args) for o in obj)
[deoplete]   File "/Users/rcrosby/.pyenv/versions/nvim/lib/python3.5/site-packages/neovim/api/common.py", line 258, in walk
[deoplete]     return fn(obj, *args)
[deoplete]   File "/Users/rcrosby/.pyenv/versions/nvim/lib/python3.5/site-packages/neovim/api/common.py", line 158, in <lambda>
[deoplete]     return lambda o, s, m, k: f1(f2(o, s, m, k), s, m, k)
[deoplete]   File "/Users/rcrosby/.pyenv/versions/nvim/lib/python3.5/site-packages/neovim/api/common.py", line 180, in _decode_if_bytes
[deoplete]     return obj.decode(self.encoding, errors=self.encoding_errors)
[deoplete] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte
[deoplete] An error has occurred. Please execute :messages command.
```

## Generate a logfile if appropriate
[log_10096.txt](https://github.com/Shougo/deoplete.nvim/files/138657/log_10096.txt)

**Comment by Shougo** [comment]
Fixed.

**Comment by rolandcrosby** [comment]
Great, thanks for the quick fix!
