### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Alok** [Shougo/deoplete.nvim#242]
# Problems summary

I sometimes get the following error when typing in a python file.

## Environment Information

 * OS: OSX 10.11.4
 * Neovim version: latest build from git

## Traceback

```
[deoplete] An error has occurred. Please execute :messages command.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 150, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 321, in gather_candidates
[deoplete]     name, type_, desc, abbr = self.parse_completion(c, tmp_filecache)
[deoplete]   File "/Users/alokbeniwal/.config/nvim/bundle/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py", line 202, in parse_completion
[deoplete]     line = lines[i].lstrip()
[deoplete] IndexError: list index out of range
```

**Comment by tweekmonster** [comment]
Hi @Alok.  Would you mind moving this issue to https://github.com/zchee/deoplete-jedi
