### ISSUE TITLE
Get some error with file source

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#291]
# Problems summary
I have test with just only one plugin, deoplete, get a lot error message.

## Expected
filename completion works well

## Environment Information

 * OS:arch

## CheckHealth!

```
No matching autocommands
Checking: Python 2
  Executable: /usr/bin/python2
  Python Version: 2.7.11
  python2-neovim Version: 0.1.9 (up to date)
  Messages:
    * Warning: "g:python_host_prog" is not set.  Searching for python2 in the
      environment.

Checking: Python 3
  Executable: /usr/bin/python3
  Python Version: 3.5.1
  python3-neovim Version: 0.1.9 (up to date)
  Messages:
    * Warning: "g:python3_host_prog" is not set.  Searching for python3 in
      the environment.

Checking: Remote Plugins
  Status: Up to date
```
 

## Provide a minimal init.vim with less than 50 lines (Required!)
test with localtest/test.vim in curren repo.
```vim
exec "set rtp+=" . fnamemodify(expand('<sfile>'), ':h:h')
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_camel_case = 1
let g:deoplete#enable_refresh_always = 1
let g:deoplete#max_abbr_width = 0
let g:deoplete#max_menu_width = 0
let g:deoplete#omni#input_patterns = get(g:,'deoplete#omni#input_patterns',{})
let g:deoplete#omni#input_patterns.java = [
            \'[^. \t0-9]\.\w*',
            \'[^. \t0-9]\->\w*',
            \'[^. \t0-9]\::\w*',
            \]
let g:deoplete#omni#input_patterns.jsp = ['[^. \t0-9]\.\w*']
let g:deoplete#omni#input_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
"call deoplete#custom#set('omni', 'min_pattern_length', 0)
inoremap <expr><C-h> deoplete#mappings#smart_close_popup()."\<C-h>"
inoremap <expr><BS> deoplete#mappings#smart_close_popup()."\<C-h>"
set isfname-==

```

## The reproduce ways from neovim starting (Required!)

 1. nvim -u localtest/test.vim
 2. complete file name.

## Upload the log file
```
[deoplete] Traceback (most recent call last): [deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 46, in completion_beg
in                                                                                                                                                     
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                         
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 74, in gather_candida
tes                                                                                                                                                    
[deoplete]     results = self.gather_results(context)                                                                                                  
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 125, in gather_result
s                                                                                                                                                      
[deoplete]     context['candidates'] = source.gather_candidates(context)                                                                               
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/sources/file.py", line 39, in gather_can
didates                                                                                                                                                
[deoplete]     p = self.__longest_path_that_exists(context, context['input'])                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/sources/file.py", line 61, in __longest_
path_that_exists                                                                                                                                       
[deoplete]     self.__isfname, input_str) else [input_str]                                                                                             
[deoplete]   File "/usr/lib/python3.5/re.py", line 203, in split                                                                                       
[deoplete]     return _compile(pattern, flags).split(string, maxsplit)                                                                                 
[deoplete] ValueError: split() requires a non-empty pattern match.                                                                                     
[deoplete] An error has occurred. Please execute :messages command.                                                                                    
[deoplete] Traceback (most recent call last):                                                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 46, in completion_beg
in                                                                                                                                                     
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                         
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 74, in gather_candida
tes                                                                                                                                                    
[deoplete]     results = self.gather_results(context)
[deoplete] p = self.__longest_path_that_exists(context, context['input'])                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/sources/file.py", line 61, in __longest_
path_that_exists                                                                                                                                       
[deoplete]     self.__isfname, input_str) else [input_str]                                                                                             
[deoplete]   File "/usr/lib/python3.5/re.py", line 203, in split                                                                                       
[deoplete]     return _compile(pattern, flags).split(string, maxsplit)                                                                                 
[deoplete] ValueError: split() requires a non-empty pattern match.                                                                                     
[deoplete] An error has occurred. Please execute :messages command.                                                                                    
[deoplete] Traceback (most recent call last):                                                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 46, in completion_beg
in                                                                                                                                                     
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                         
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 74, in gather_candida
tes                                                                                                                                                    
[deoplete]     results = self.gather_results(context)                                                                                                  
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 125, in gather_result
s                                                                                                                                                      
[deoplete]     context['candidates'] = source.gather_candidates(context)                                                                               
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/sources/file.py", line 39, in gather_can
didates                                                                                                                                                
[deoplete]     p = self.__longest_path_that_exists(context, context['input'])                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/sources/file.py", line 61, in __longest_
path_that_exists                                                                                                                                       
[deoplete]     self.__isfname, input_str) else [input_str]                                                                                             
[deoplete]   File "/usr/lib/python3.5/re.py", line 203, in split                                                                                       
[deoplete]     return _compile(pattern, flags).split(string, maxsplit)                                                                                 
[deoplete] ValueError: split() requires a non-empty pattern match.
[deoplete] context['candidates'] = source.gather_candidates(context)                                                                               
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/sources/file.py", line 39, in gather_can
didates                                                                                                                                                
[deoplete]     p = self.__longest_path_that_exists(context, context['input'])                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/sources/file.py", line 61, in __longest_
path_that_exists                                                                                                                                       
[deoplete]     self.__isfname, input_str) else [input_str]                                                                                             
[deoplete]   File "/usr/lib/python3.5/re.py", line 203, in split                                                                                       
[deoplete]     return _compile(pattern, flags).split(string, maxsplit)                                                                                 
[deoplete] ValueError: split() requires a non-empty pattern match.                                                                                     
[deoplete] An error has occurred. Please execute :messages command.                                                                                    
[deoplete] Traceback (most recent call last):                                                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 46, in completion_beg
in                                                                                                                                                     
[deoplete]     complete_position, candidates = self.gather_candidates(context)                                                                         
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 74, in gather_candida
tes                                                                                                                                                    
[deoplete]     results = self.gather_results(context)                                                                                                  
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 125, in gather_result
s                                                                                                                                                      
[deoplete]     context['candidates'] = source.gather_candidates(context)                                                                               
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/sources/file.py", line 39, in gather_can
didates                                                                                                                                                
[deoplete]     p = self.__longest_path_that_exists(context, context['input'])                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/sources/file.py", line 61, in __longest_
path_that_exists                                                                                                                                       
[deoplete]     self.__isfname, input_str) else [input_str]
```

**Comment by wsdjeg** [comment]
@Shougo `git reset --hard HEAD^1` make file source works well, so I think it maybe due to the laste commit https://github.com/Shougo/deoplete.nvim/commit/eac8020ef6f740df9109fa557b46a488f98103f1

**Comment by Shougo** [comment]
Please upload the correct reproduce ways.
I cannot reproduce it.

**Comment by wsdjeg** [comment]
just open nvim with this vimrc.and type i to insert mide. then type `~/`

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
thank you very much, it works well now.

**Comment by exAspArk** [comment]
Hi, I have a similar problem when I edit YAML files:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/exaspark/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 100, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/Users/exaspark/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/file.py", line 40, in gather_candidates
[deoplete]     p = self.__longest_path_that_exists(context, context['input'])
[deoplete]   File "/Users/exaspark/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/file.py", line 62, in __longest_path_that_exists
[deoplete]     self.__isfname, input_str)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 203, in split
[deoplete]     return _compile(pattern, flags).split(string, maxsplit)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 293, in _compile
[deoplete]     p = sre_compile.compile(pattern, flags)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_compile.py", line 536, in compile
[deoplete]     p = sre_parse.parse(p, flags)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 829, in parse
[deoplete]     p = _parse_sub(source, pattern, 0)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 437, in _parse_sub
[deoplete]     itemsappend(_parse(source, state))
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 778, in _parse
[deoplete]     p = _parse_sub(source, state)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 437, in _parse_sub
[deoplete]     itemsappend(_parse(source, state))
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 778, in _parse
[deoplete]     p = _parse_sub(source, state)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 437, in _parse_sub
[deoplete]     itemsappend(_parse(source, state))
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 638, in _parse
[deoplete]     source.tell() - here + len(this))
[deoplete] sre_constants.error: nothing to repeat at position 4
[deoplete] Could not get completions from: file.  Use :messages for error details.
```

The version of deoplete before this commit https://github.com/Shougo/deoplete.nvim/commit/981aedb97b0bc75331eccddef5794c8e3899b12d works without the error.

Any ideas how to fix it?
Thanks

**Comment by Shougo** [comment]
@exAspArk It seems the regexp pattern error.
It is another issue.
Please create new issue for it with minimal init.vim and the reproduce way.
I must reproduce it.
