### ISSUE TITLE
UnicodedecodeError when entering insert mode and typing.

### ISSUE THREAD

**Issue by Unode** [Shougo/deoplete.nvim#295]
# Problems summary
Whenever I start nvim and enter insert mode I always get:

```
error caught in async handler 'deoplete_on_event [{b'max_abbr_width': 178, b'sources': [], b'bufname': b'test.py', b'changedtick': 3, b'bufnr': 1, b'camelcase': 0, b'complete_str': b'', b'runtimepath': b'/home/unode/.config/nvim,/home/unode/.vim/bundle/vundle,/home/unode/.vim/bundle/ag.nvim,/home/unode/.vim/bundle/splice.vim
...
b'start_complete': b'\x80\xfdR(deoplete_start_complete)', b'bufvars': {}, b'next_input': b'pass', b'keyword_patterns': b'[a-zA-Z_][a-zA-Z@0-9_\xc3\x80-\xc3\xbf]*', b'dict__dictionary': b'', b'delay': 0, b'position': [0, 2, 5, 0], b'input': b'    '}]':
UnicodeDecodeError('utf-8', b'\x80\xfdR(deoplete_start_complete)', 0, 1, 'invalid start byte')
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/neovim/plugin/host.py", line 91, in _on_notification
    handler(*args)
  File "/usr/lib64/python3.4/site-packages/neovim/plugin/host.py", line 160, in decoder
    return fn(*walk(decode_if_bytes, args, decode))
  File "/usr/lib64/python3.4/site-packages/neovim/api/common.py", line 168, in walk
    return list(walk(fn, o, *args) for o in obj)
  File "/usr/lib64/python3.4/site-packages/neovim/api/common.py", line 168, in <genexpr>
    return list(walk(fn, o, *args) for o in obj)
  File "/usr/lib64/python3.4/site-packages/neovim/api/common.py", line 171, in walk
    obj.items())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

I have to disable deoplete.nvim plugin to be able to use nvim as the error shows up at almost every keypress.

## Expected
This is my first time trying this plugin. I would expect no errors at least.

It seems the problem starts at `b'start_complete': b'\x80\xfdR(deoplete_start_complete)'`. At least the Exception mentions `0x80` which is exactly how the payload starts.

## Neovim Python Diagnostic
```
NVIM 0.1.4
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -march=x86-64 -pipe -Wno-error -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/var/tmp/portage/app-editors/neovim-0.1.4/work/neovim-0.1.4_build/config -I/var/tmp/portage/app-editors/neovim-0.1.4/work/neovim-0.1.4/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.1.4/work/neovim-0.1.4_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.1.4/work/neovim-0.1.4_build/include
Compiled by portage@andromeda.sabayon.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

Plugin 'gmarik/vundle'
Plugin 'Shougo/deoplete.nvim'

" Activate deoplete by default
let g:deoplete#enable_at_startup = 1

" Finish setup of plugins/bundles
call vundle#end()
```

**Comment by yevhen-m** [comment]
I have the same issue. I've just updated deoplete.

**Comment by Deraen** [comment]
Probably caused by commit https://github.com/Shougo/deoplete.nvim/commit/0b84100ae775a6a1d1436c81a71bbeaeba241ab6 and the problem seems to be the representation of `\<Plug>` character.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/292
