### ISSUE TITLE
Failed to load python host

### ISSUE THREAD

**Issue by vshl** [Shougo/deoplete.nvim#31]
Today I updated deoplete.vim and I'm getting this error on python files:
```
Vim(if):Channel was closed by the client
Error detected while processing function deoplete#init#enable..remote#define#CommandBootstrap..remote#host#Require..<SNR>32_RequirePythonHost:
line   21:
E605: Exception not caught: Failed to load Python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and ope
ning the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.
```

~/.nvimlog
```
2015/08/14 18:23:11 [info @ main_loop:558] 3477 - Starting Neovim main loop.
2015/08/14 18:23:20 [error @ forward_stderr:338] 3477 - Channel 2 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/neovim/__init__.py", line 66, in start_host
    host.start(plugins)
  File "/usr/local/lib/python3.4/site-packages/neovim/plugin/host.
2015/08/14 18:23:20 [error @ forward_stderr:338] 3477 - Channel 2 stderr: py", line 47, in start
    lambda: self._load(plugins))
  File "/usr/local/lib/python3.4/site-packages/neovim/api/common.py", line 244, in run
    self._session.run(filter_request_cb, filter_notification_cb, setup_cb)
  File "/usr/local/lib/python3.4/site
2015/08/14 18:23:20 [error @ forward_stderr:338] 3477 - Channel 2 stderr: -packages/neovim/msgpack_rpc/session.py", line 118, in run
    raise self._setup_exception
  File "/usr/local/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 106, in on_setup
    setup_cb()
  File "/usr/local/lib/python3.4/site-packages/n
2015/08/14 18:23:20 [error @ forward_stderr:338] 3477 - Channel 2 stderr: eovim/plugin/host.py", line 47, in <lambda>
    lambda: self._load(plugins))
  File "/usr/local/lib/python3.4/site-packages/neovim/plugin/host.py", line 87, in _load
    file, pathname, description = find_module(name, [directory])
  File "/usr/local/lib/p
2015/08/14 18:23:20 [error @ forward_stderr:338] 3477 - Channel 2 stderr: ython3.4/site-packages/neovim/compat.py", line 29, in find_module
    return original_find_module(fullname, path)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py", line 297, in find_module
    raise
2015/08/14 18:23:20 [error @ forward_stderr:338] 3477 - Channel 2 stderr: ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'deoplete'

2015/08/14 18:23:20 [error @ call_set_error:748] 3477 - msgpack-rpc: Channel was closed by the client
```

Is it a problem with deoplete or something else entirely? Thanks for the help.

**Comment by Shougo** [comment]
You should update neovim and neovim Python3 module by pip.

**Comment by vshl** [comment]
I did try that. It's still the same for me. I disabled all plugins and loaded only deoplete yet I get the error. It was working fine until the last update. Is there a way I can debug it further?

**Comment by Shougo** [comment]
Really?  OK.  I will try it.

**Comment by Shougo** [comment]
I think you should execute `:UpdateRemotePlugins` command.
Please try it.

**Comment by vshl** [comment]
Perfect that worked great. Thanks a lot. Great work behind this plugin. :+1:
