### ISSUE TITLE
Obscure error - Not sure what to report

### ISSUE THREAD

**Issue by mhartington** [Shougo/deoplete.nvim#35]
Occasionally I'll get this error 

<img width="1237" alt="screen shot 2015-08-20 at 1 26 18 pm" src="https://cloud.githubusercontent.com/assets/2835826/9390459/3e9a0a78-473f-11e5-9afc-3661362a706f.png">

With `:DeopleteMessages` showing this for the output.

```
Error detected while processing function remote#define#CommandBootstrap:
line    5:
NvimError(b'Vim(edit):E37: No write since last change (add ! to override)',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python3.4/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python3.4/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/local/lib/python3.4/site-packages/neovim/plugin/host.py", line 141, in <lambda>
    decoder = lambda fn, hook, *args: fn(*hook.walk(args))
  File "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 59, in print_error
    self.vim.command('edit ' + self.msgfile)
neovim.api.nvim.NvimError: b'Vim(edit):E37: No write since last change (add ! to override)'
E171: Missing :endif
``` 
Neovim info:
```
NVIM 0.0.0-alpha+201508201245 (compiled Aug 20 2015 13:32:12)
Commit: f253c8d9b4ab0b31ce0d9a6a1b60428785d93d50
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim201
50820-24077-tn0tiq/build/config -I/tmp/neovim20150820-24077-tn0tiq/src -I/tmp/neovim20150820-24077-tn0tiq/deps-build/usr/include -I/tmp/neovim20150820-24077-tn0tiq/deps-build/usr/include -I/tmp/neovim20150820
-24077-tn0tiq/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20150820-24077-tn0tiq/deps-build/usr/include -I/tmp/neovim20150820-24077-tn0tiq/deps-build/usr/include -I/tmp/neovim20150820-24077-tn0tiq/deps-buil
d/usr/include -I/tmp/neovim20150820-24077-tn0tiq/deps-build/usr/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/u
sr/include -I/tmp/neovim20150820-24077-tn0tiq/build/src/nvim/auto -I/tmp/neovim20150820-24077-tn0tiq/build/include
Compiled by mhartington@Mikes-MBP.home

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

OSX

What other information do you need from me?

**Comment by Shougo** [comment]
Please execute `:set hidden` and `:DeopleteMessages` commands.
You should read `:help E37`.

**Comment by mhartington** [comment]
```
Traceback (most recent call last):
  File "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 92, in completion_begin
    self.deoplete.gather_candidates(context)
  File "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 96, in gather_candidates
    results = self.gather_results(context)
  File "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 139, in gather_results
    context['candidates'] = source.gather_candidates(context)
  File "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 49, in gather_candidates
    mtime = getmtime(tags_file)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/r7/jttq31p92l96ksjpw92c589r0000gn/T/nvimlXDMa3/2'
Traceback (most recent call last):
  File "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 92, in completion_begin
    self.deoplete.gather_candidates(context)
  File "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 96, in gather_candidates
    results = self.gather_results(context)
  File "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 139, in gather_results
    context['candidates'] = source.gather_candidates(context)
  File "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/sources/tag.py", line 49, in gather_candidates
    mtime = getmtime(tags_file)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/r7/jttq31p92l96ksjpw92c589r0000gn/T/nvimlXDMa3/2'
```

**Comment by Shougo** [comment]
Thanks.  Fixed it.
