### ISSUE TITLE
Deoplete won't initialize properly, receive E691: Can only compare List with List upon entering insert mode

### ISSUE THREAD

**Issue by NickHurst** [Shougo/deoplete.nvim#368]
# Problems summary
Deoplete does not seem to initialize correctly, upon entering insert mode I recieve this error:

```
Error detected while processing function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize:
line   31:
E691: Can only compare List with List
```

Running `:UpdateRemotePlugins` causes this error:

```
Encountered Exception loading plugin at $HOME/.config/nvim/rplugin/python3/deoplete: Notification handler for "deoplete_auto_completion_begin" is already registered
Traceback (most recent call last):
  File "$HOME/Library/Python/3.5/lib/python/site-packages/neovim/plugin/host.py", line 133, in _load
    self._discover_classes(module, handlers, path)
  File "$HOME/Library/Python/3.5/lib/python/site-packages/neovim/plugin/host.py", line 165, in _discover_classes
    self._discover_functions(plugin, handlers, plugin_path)
  File "$HOME/Library/Python/3.5/lib/python/site-packages/neovim/plugin/host.py", line 196, in _discover_functions
    'already registered').format(method))
Exception: Notification handler for "deoplete_auto_completion_begin" is already registered
remote/host: python3 host registered plugins ['deoplete']
remote/host: generated rplugin manifest: $HOME/.local/share/nvim/rplugin.vim
```

## Expected
Deoplete initialization.

## Environment Information

 * OS: macOS Sierra 10.12.1 (16B2555)

 * nvim-python-doctor result

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: "nvim" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`

## terminfo
  - ERROR: key_backspace (kbs) entry is ^H (ASCII DELETE): key_backspace=^H,

    - SUGGESTIONS:
      - Set key_backspace to \177 (ASCII BACKSPACE). Run these commands:
          infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
          tic $TERM.ti
      - See https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim Version: 0.1.10
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim Version: 0.1.10
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

## Neovim Python Diagnostic

Neovim Version: NVIM 0.1.6 Build type: RelWithDebInfo

## Python Version

```
2.7.12 (default, Oct 11 2016, 05:24:00)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
function! UpdateRPlugin(info)
  if has('nvim')
    silent UpdateRemotePlugins
    echomsg 'rplugin updated: ' . a:info['name'] . ', restart vim for changes'
  endif
endfunction

call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

" Use deoplete.
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. Open nvim `nvim somefile`
 2. Enter insert mode `i`

**Comment by Shougo** [comment]
OK.
Your deoplete is too old.  Please update it.
