### ISSUE TITLE
Deoplete crashes when UltiSnips is used

### ISSUE THREAD

**Issue by siavasht** [Shougo/deoplete.nvim#381]
# Problems summary
Error messages are printed when using deoplete along with UltiSnips plugin.

## Expected
Normal use, the errors appear even before doing any edit.

## Environment Information

 * OS: Ubuntu 15.10

 * `:CheckHealth` result:

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: ".vim" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xclip

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.10
  - INFO: python2-neovim Version: 0.1.11
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.4.3
  - INFO: python3-neovim Version: 0.1.11
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin()
  Plug 'SirVer/ultisnips'
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. Add UltiSnips to packages
 2. Start editing

**Comment by Shougo** [comment]
Reproduced.  But it is reproduced without deoplete.
It seems neovim or neovim-python problem.
Please create new issue in the repository.

**Comment by siavasht** [comment]
hmmm, on my setup I don't get the error without deoplete. Just to make sure, the error message I get is the following:

```

Traceback (most recent call last):
  File "/home/siavash/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 62, in on_event
    self.__deoplete.on_event(context)
  File "/home/siavash/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 377, in on_event
    for source_name, source in self.itersource(context):
  File "/home/siavash/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 194, in itersource
    if not source.is_initialized and hasattr(source, 'on_init'):
AttributeError: 'Source' object has no attribute 'is_initialized'
```

**Comment by Shougo** [comment]
I have tested it, but the error is not occured.

**Comment by Shougo** [comment]
And you should not use Ubuntu 15.10.  It is too old and not supported yet.
