### ISSUE TITLE
E874: (NFA) Could not pop the stack

### ISSUE THREAD

**Issue by mhinz** [Shougo/deoplete.nvim#382]
### Environment

- **OS**: `macOS Sierra`
- **Neovim version**: `v0.2.0-52-g0213e99` and `v0.1.6`
- **Python version**: `Python 3.5.1`
- **Python package version**: `0.1.11`

### Minimal init.vim

```vim
set runtimepath+=~/.vim/bundle/deoplete.nvim
let g:deoplete#enable_at_startup = 1

set statusline=%!SetStatusline()

function! SetStatusline()
  return 'foo'
endfunction
```

### Problem

Simply typing `~/.` in any `ft=ruby` buffer yields the following error:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/mhi/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/source/omni.py", line 94, in gather_candidates
[deoplete]     self.__omnifunc, 0, context['complete_str'])
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 230, in call
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):W, [2016-11-16T13:03:58.873535 #6460]  WARN -- Neovim::Host: got unexpected error #<ArgumentError: Vim(let):E874: (NFA) Could
not pop the stack !>'
[deoplete] Error occurred calling omnifunction: rubycomplete#Complete.  Use :messages for error details.
```

Commenting out the `set statusline...` in the init.vim makes it work.

I'm not sure if it's a bug in deoplete or a bug in Neovim triggered by deoplete. :-) And I have no idea why any of this should be related to the `statusline`. Seems like a bug in Neovim to me, eh?

**Comment by mhinz** [comment]
Okay, I can reproduce it without deoplete. Taking it to the Neovim issue tracker..

**Comment by alem0lars-yoroi** [comment]
I'm still having the same issue, is that solved?

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/etc/xdg/nvim/cache/vimplug/deoplete.nvim/rplugin/python3/deoplete/
source/omni.py", line 96, in gather_candidates
[deoplete]     self.__omnifunc, 0, context['complete_str'])
[deoplete]   File "/usr/lib64/python3.4/site-packages/neovim/api/nvim.py", line 230, i
n call
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]   File "/usr/lib64/python3.4/site-packages/neovim/api/nvim.py", line 131, i
n request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/lib64/python3.4/site-packages/neovim/msgpack_rpc/session.py",
line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):W, [2017-02-09T09:09:59.432917 #27
997]  WARN -- Neovim::Host: got unexpected error #<ArgumentError: Vim(let):E874: (NFA)
 Could not pop the stack !>'
[deoplete] Error occurred calling omnifunction: rubycomplete#Complete.  Use :messages
for error details.
```

**Comment by Shougo** [comment]
@alem0lars-yoroi This is not deoplete problem.
It is neovim error.  You should create new issue with the minimal config and the reproduce ways from neovim starting.
