### ISSUE TITLE
Get a lot error when edit muttrc.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#400]
I am using neovim + deoplete, both of them is master branch.
here is the link of the file,
https://github.com/wsdjeg/DotFiles/blob/master/muttrc

step:
1. nvim muttrc
2. `:128`
3. Type `A`, try to insert something at the end of line 128.

here is error message:
```

[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 100, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/file.py", line 40, in gather_candidates
[deoplete]     p = self.__longest_path_that_exists(context, context['input'])
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/file.py", line 62, in __longest_path_that_exists
[deoplete]     self.__isfname, input_str)
[deoplete]   File "/usr/lib/python3.5/re.py", line 203, in split
[deoplete]     return _compile(pattern, flags).split(string, maxsplit)
[deoplete]   File "/usr/lib/python3.5/re.py", line 293, in _compile
[deoplete]     p = sre_compile.compile(pattern, flags)
[deoplete]   File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
[deoplete]     p = sre_parse.parse(p, flags)
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
[deoplete]     p = _parse_sub(source, pattern, 0)
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
[deoplete]     itemsappend(_parse(source, state))
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 778, in _parse
[deoplete]     p = _parse_sub(source, state)
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
[deoplete]     itemsappend(_parse(source, state))
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 778, in _parse
[deoplete]     p = _parse_sub(source, state)
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
[deoplete]     itemsappend(_parse(source, state))
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 638, in _parse
[deoplete]     source.tell() - here + len(this))
[deoplete] sre_constants.error: nothing to repeat at position 4
[deoplete] Could not get completions from: file.  Use :messages for error details.
```

**Comment by tweekmonster** [comment]
I'm unable to reproduce this.  What's the value of `isfname`?

**Comment by wsdjeg** [comment]
it is `@,48-57,/,.,-,_,+,,,#,$,%,~`

**Comment by gigavinyl** [comment]
I get similar errors when editing config files.

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please upload the minimal init.vim with `isfname` configuration.

@gigavinyl I cannot reproduce the problem.
Please upload the minimal init.vim with `isfname` configuration.

**Comment by tweekmonster** [comment]
@wsdjeg sorry I didn't respond.  I was unable to reproduce with that `isfname` value.  I tested with directories and filenames with regex special characters in them without issues.

@gigavinyl are you also using Python 3.5?

**Comment by gigavinyl** [comment]
@tweekmonster No, I'm using Python 3.4.5.

**Comment by wsdjeg** [comment]
I will show mini init.vim next week.

**Comment by wsdjeg** [comment]
@Shougo, I can not make mini vimrc, I have test in my dofiles, even if I disable most of my scripts this error still happened. It is too strange.

**Comment by Shougo** [comment]
@wsdjeg Please don't use your dotfiles.
Please create minimal vimrc from scratch.

**Comment by wsdjeg** [comment]
@Shougo I will look into in latter.

**Comment by wsdjeg** [comment]
@Shougo @tweekmonster I have test it out, and here is the reproduce step:
use this vim file as init.vim: `nvim -u deoplete_file.vim`.
deoplete_file.vim
```viml
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/dein.vim
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'

call dein#begin('~/.cache/vimfiles')
call dein#add('Shougo/deoplete.nvim', {'on_i' : 1})
call dein#add('Shougo/neco-syntax', {'on_i': 1})
call dein#end()
filetype plugin indent on
syntax enable
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_camel_case = 1
let g:deoplete#enable_refresh_always = 1
let g:deoplete#max_abbr_width = 0
let g:deoplete#max_menu_width = 0
let g:deoplete#omni#input_patterns = get(g:,'deoplete#omni#input_patterns',{})
let g:deoplete#omni#input_patterns.java = [
            \'[^. \t0-9]\.\w*',
            \'[^. \t0-9]\->\w*',
            \'[^. \t0-9]\::\w*',
            \]
let g:deoplete#omni#input_patterns.jsp = ['[^. \t0-9]\.\w*']
let g:deoplete#omni#input_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
let g:deoplete#ignore_sources = {}
"call deoplete#custom#set('omni', 'min_pattern_length', 0)
inoremap <expr><C-h> deoplete#mappings#smart_close_popup()."\<C-h>"
inoremap <expr><BS> deoplete#mappings#smart_close_popup()."\<C-h>"
set isfname-==
```
muttrc file is : https://github.com/wsdjeg/DotFiles/blob/master/muttrc

then the step is:
1. vim -u deoplete_file.vim
2. :e muttrc
3. :128
4. type normal `A`. you will see : 
```log

"muttrc" 129L, 4473C
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 103, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/file.py", line 40, in gather_candidates
[deoplete]     p = self.__longest_path_that_exists(context, context['input'])
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/file.py", line 62, in __longest_path_that_exists
[deoplete]     self.__isfname, input_str)
[deoplete]   File "/usr/lib/python3.5/re.py", line 203, in split
[deoplete]     return _compile(pattern, flags).split(string, maxsplit)
[deoplete]   File "/usr/lib/python3.5/re.py", line 293, in _compile
[deoplete]     p = sre_compile.compile(pattern, flags)
[deoplete]   File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
[deoplete]     p = sre_parse.parse(p, flags)
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 829, in parse

[deoplete]     p = _parse_sub(source, pattern, 0)
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
[deoplete]     itemsappend(_parse(source, state))
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 778, in _parse
[deoplete]     p = _parse_sub(source, state)
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
[deoplete]     itemsappend(_parse(source, state))
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 778, in _parse
[deoplete]     p = _parse_sub(source, state)
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
[deoplete]     itemsappend(_parse(source, state))
[deoplete]   File "/usr/lib/python3.5/sre_parse.py", line 638, in _parse
[deoplete]     source.tell() - here + len(this))
[deoplete] sre_constants.error: nothing to repeat at position 4
[deoplete] Could not get completions from: file.  Use :messages for error details.
```

**Comment by Shougo** [comment]
OK.  I will test it.
