### ISSUE TITLE
Errors when entering insert in PHP file

### ISSUE THREAD

**Issue by ChrisBFusion** [Shougo/deoplete.nvim#434]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When entering a PHP file, deoplete immediately generates errors.

## Expected
Deoplete to provide completions in PHP files.

## Environment Information

 * deoplete version(SHA1): 9f62f1af933f5852b8d797dde4f8d36997a66941
SHA1(/Users/chris/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/plugin/deoplete.vim)

 * OS: MacOS 10.12.3

 * neovim version: 0.1.7

 * `:CheckHealth` result(neovim ver.0.1.5-452+):
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2.7 in the environment.
  - INFO: There are multiple python2.7 executables found.  Set "g:python_host_prog" to avoid surprises.
  - INFO: Executable: /opt/local/bin/python2.7
  - INFO: Other python executable: /usr/bin/python2.7
  - INFO: Python2 version: 2.7.13
  - INFO: python2.7-neovim version: 0.1.13
  - SUCCESS: Latest python2.7-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python in the environment.
  - INFO: There are multiple python executables found.  Set "g:python3_host_prog" to avoid surprises.
  - INFO: Executable: /opt/local/bin/python
  - INFO: Other python executable: /usr/bin/python
  - INFO: Python3 version: 3.6.0
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
  - INFO: Host Executable: /opt/local/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.1
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
g:spacevim_version = '0.1.0-dev'
g:spacevim_force_global_config = 0
g:spacevim_smartcloseignoreft = ['help']
g:spacevim_default_indent = 2
g:spacevim_enable_javacomplete2_py = 0
g:spacevim_enable_vimfiler_welcome = 1
g:spacevim_colorscheme_default = 'desert'
g:spacevim_warning_symbol = '⚠'
g:spacevim_simple_mode = 0
g:spacevim_colorscheme = 'base16-solarized-dark'
g:spacevim_enable_guicolors = 1
g:spacevim_custom_plugins = [['tpope/vim-obsession'], ['dhruvasagar/vim-prosession'], ['terryma/vim-multiple-cursors']]
g:spacevim_hiddenfileinfo = 1
g:spacevim_error_symbol = '✖'
g:spacevim_vim_plug_installed = 0
g:spacevim_windows_leader = 's'
g:spacevim_wildignore = '*/tmp/*,*.so,*.swp,*.zip,*.class,tags,*.jpg,*.ttf,*.TTF,*.png,*/target/*,.git,.svn,.hg,.DS_Store'
g:spacevim_use_colorscheme = 1
g:spacevim_plugin_manager = 'dein'
g:spacevim_enable_neocomplcache = 0
g:spacevim_enable_debug = 0
g:spacevim_vim_help_language = 'en'
g:spacevim_lint_on_save = 1
g:spacevim_dein_installed = 1
g:spacevim_autocomplete_method = 'deoplete'
g:spacevim_unite_leader = 'f'
g:spacevim_enable_ycm = 0
g:spacevim_enable_powerline_fonts = 1
g:spacevim_plugin_groups_exclude = []
g:spacevim_neobundle_installed = 0
g:spacevim_disabled_plugins = []
g:spacevim_guifont = ''
g:spacevim_plugin_groups = ['web', 'lang', 'edit', 'ui', 'tools', 'checkers', 'format', 'chat', 'git', 'javascript', 'ruby', 'python', 'scala', 'lang#go', 'scm', 'editing', 'indents', 'navigation', 'misc', 'core', 'unite', 'github', 'denite', 'ctrlp', 'autocomplete
', 'nvim', 'osx', 'colorscheme']
g:spacevim_enable_googlesuggest = 0
g:spacevim_language = ''
g:spacevim_enable_neomake = 1
g:spacevim_plugin_bundle_dir = '/Users/chris/.cache/vimfiles/'
g:spacevim_hosts_url = 'https://raw.githubusercontent.com/racaljk/hosts/master/hosts'
g:spacevim_smartcloseignorewin = ['__Tagbar__', 'vimfiler:default']
g:spacevim_altmoveignoreft = ['Tagbar', 'vimfiler']
g:spacevim_enable_cursorcolumn = 0
g:spacevim_realtime_leader_guide = 0
g:spacevim_checkinstall = 1
g:spacevim_plugin_name = 'gruvbox'
g:spacevim_enable_cursorline = 0
g:spacevim_debug_level = 1
g:spacevim_filemanager = 'vimfiler'
g:spacevim_src_root = 'E:\sources\'
g:spacevim_max_column = 120
```

## The reproduce ways from neovim starting (Required!)

 1. Place cursor in PHP file.
 2. Within PHP code, enter insert mode.
 3. Watch ex statusline print errors.

## Generate a logfile if appropriate
:message output:
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/chris/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_results
[deoplete]     charpos = source.get_complete_position(ctx)
[deoplete]   File "/Users/chris/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/omni.py", line 60, in get_complete_position
[deoplete]     m = re.search('(' + input_pattern + ')$', context['input'])
[deoplete]   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 182, in search
[deoplete]     return _compile(pattern, flags).search(string)
[deoplete]   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 301, in _compile
[deoplete]     p = sre_compile.compile(pattern, flags)
[deoplete]   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 562, in compile
[deoplete]     p = sre_parse.parse(p, flags)
[deoplete]   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 856, in parse
[deoplete]     p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, False)
[deoplete]   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 415, in _parse_sub
[deoplete]     itemsappend(_parse(source, state, verbose))
[deoplete]   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 763, in _parse
[deoplete]     p = _parse_sub(source, state, sub_verbose)
[deoplete]   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 415, in _parse_sub
[deoplete]     itemsappend(_parse(source, state, verbose))
[deoplete]   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 501, in _parse
[deoplete]     code = _escape(source, this, state)
[deoplete]   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 401, in _escape
[deoplete]     raise source.error("bad escape %s" % escape, len(escape))
[deoplete] sre_constants.error: bad escape \h at position 1
[deoplete] Could not get completions from: omni.  Use :messages for error details.
```

## Upload the log file
[log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/780977/log_py3_rplugin.txt)

**Comment by Shougo** [comment]
I think deoplete PHP omni configuration is wrong in SpaceVim.
deoplete does not set the pattern.

@wsdjeg Ping.

**Comment by Shougo** [comment]
I get it.  This pattern is wrong.
It must be Python3 regexp.
This is Vim script regexp.

https://github.com/SpaceVim/SpaceVim/blob/91b3dd85c30551a910949bdf3ed8f2bab11942ae/config/plugins/deoplete.vim#L21

**Comment by wsdjeg** [comment]
Sorry, I will look into it.

**Comment by wsdjeg** [comment]
@Shougo I am not family with py3 regexp, so how should I set the pattern of php?

**Comment by Shougo** [comment]
It must be:

```vim
let g:deoplete#omni#input_patterns.php = '\w*\|[^. \t]->\w*|\w*::\w*'
```

**Comment by v-leonhou** [comment]
i got the same error @wsdjeg @Shougo   have you fixed it yet

**Comment by v-leonhou** [comment]
i have configed let g:deoplete#omni#input_patterns.php = '\w*|[^. \t]->\w*|\w*::\w*' ,but the error didn't disappear @wsdjeg @Shougo

**Comment by Shougo** [comment]
I think the problem is fixed in the latest of SpaceVim.
Your SpaceVim is the latest version?

@wsdjeg Ping.

**Comment by wsdjeg** [comment]
I have fixed it.

**Comment by dbrw** [comment]
I am using `let g:deoplete#omni#input_patterns.php = '\w*|[^. \t]->\w*|\w*::\w*' ` and getting another error when starting nvim:
```
E121: Undefined variable: Error detected while processing /home/dim/.SpaceVim.d/init.vim:
line   35:
E121: Undefined variable: g:deoplete#omni#input_patterns
Press ENTER or type command to continue
g:deoplete#omni#input_patterns
```

line 35 is `let g:deoplete#omni#input_patterns.php = '\w*|[^. \t]->\w*|\w*::\w*'`

note: I also have updated spacevim with `:SPUpdate SpaceVim`

**Comment by wsdjeg** [comment]
SpaceVim have set it. no need set it again. BTW you should read tutorial of viml. you should defind the dict before set the key in it.

**Comment by Shougo** [comment]
@dbrw Please use `g:deoplete#omni_patterns` instead.

```vim
let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.php = '\w*|[^. \t]->\w*|\w*::\w*'
```
