### ISSUE TITLE
Deoplete emits stacktrace in commandline edit mode.

### ISSUE THREAD

**Issue by raichoo** [Shougo/deoplete.nvim#456]
# Problems summary

Deoplete emits a traceback when editing in command line edit mode

## Expected

Should not happen.

## Environment Information

 * deoplete version(SHA1): 7a70f27f9ef976fc2ff365c3f7aa4567b5ea426a

 * OS: Archlinux

 * neovim version: NVIM v0.2.0-1118-g0f6608d03

 * `:CheckHealth` result(neovim ver.0.1.5-452+):

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.0
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - WARNING: `ruby` and `gem` must be in $PATH.
    - SUGGESTIONS:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
call plug#begin('~/.nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

1. record a macro that only consists of one backspace: `qa<BS>q`
2. try to edit it in command line mode `:let @a='<C-R>a`
3. enter command line edit mode by pressing `<C-f>`
4. enter insert mode by pressing A and start typing.

Stack trace should pop up after the second character or so.

## Traceback in :messages
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: around.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: omni.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: file.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: buffer.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: member.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: dictionary.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: tag.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: around.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results

[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: omni.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: file.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: buffer.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: member.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: dictionary.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 93, in gather_results
[deoplete]     ctx['encoding'], ctx['input'], charpos)
[deoplete]   File "/home/raichoo/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/util.py", line 138, in charpos2bytepos
[deoplete]     return len(bytes(input[: pos], encoding))
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 12: surrogates not allowed
[deoplete] Could not get completions from: tag.  Use :messages for error details.
```

**Comment by raichoo** [comment]
Workaround: My terminal sent an `ASCII DEL` on backspace. I've changed it to `CTRL-H`.
