### ISSUE TITLE
Errors when starting auto-completion

### ISSUE THREAD

**Issue by pehota** [Shougo/deoplete.nvim#469]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Whenever deoplete kicks in I get the bellow errors and the result is I don't have auto-completion.
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/dimitarapostolov/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/dimitarapostolov/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_length.py", line 20, in filter
[deoplete]     return [x for x in context['candidates']
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] Could not filter using: <deoplete.filter.matcher_length.Filter object at 0x110d1b6d8>.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/dimitarapostolov/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/dimitarapostolov/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_fuzzy.py", line 26, in filter
[deoplete]     return [x for x in context['candidates']
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] Could not filter using: <deoplete.filter.matcher_fuzzy.Filter object at 0x110d1b1d0>.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/dimitarapostolov/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/dimitarapostolov/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/sorter_rank.py", line 23, in filter
[deoplete]     key=lambda x: -1 * rank[x['word']]
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] Could not filter using: <deoplete.filter.sorter_rank.Filter object at 0x110d1b940>.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/dimitarapostolov/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/dimitarapostolov/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_abbr.py", line 24, in filter
[deoplete]     for candidate in context['candidates']:
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] Could not filter using: <deoplete.filter.converter_truncate_abbr.Filter object at 0x110d14cc0>.  Use :messages for error details.
```

## Expected
Not get any errors and have completion working

## Environment Information

 * deoplete version(SHA1): f583f80

 * OS: MacOS Sierra 10.12.4, Ubuntu 16.04 (LTS)

 * neovim version: 0.1.7

 * `:CheckHealth` result(neovim ver.0.1.5-452+):
```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

## tmux
  - SUCCESS: escape-time: 10ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
  - INFO: Host Executable: /Users/dimitarapostolov/.rvm/gems/ruby-2.2.1/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.3
```

## Provide a minimal init.vim with less than 50 lines (Required!)jk

```
  set runtimepath+=~/.vim/plugged/deoplete.nvim/
  let g:deoplete#enable_at_startup = 1
  let g:SuperTabDefaultCompletionType = "<c-n>"
  let g:deoplete#sources#flow#flow_bin = g:flow_path
```

## The reproduce ways from neovim starting (Required!)

1. Start neovim
2. Open a javascript file
3. write `console.` (including the dot in order to invoke the auto-completion)
4. check the status line/messages

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by sourcesoft** [comment]
I'm experiencing the same issue.

**Comment by devth** [comment]
I'm getting the same problems. After it happens I can't even quit vim. I have to kill the tmux pane forcibly.

**Comment by Shougo** [comment]
Fixed the error.

**Comment by Shougo** [comment]
The source (deoplete-flow) returns None.
I think it is not normal path.
