### ISSUE TITLE
Error after closing fugitive's gitcommit buffer

### ISSUE THREAD

**Issue by yevhen-m** [Shougo/deoplete.nvim#479]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Error on buffer save after the last update.

## Environment Information

 * deoplete version(SHA1): c202045

 * OS: OSX
 * neovim version: 0.2.0

 # Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 500
let g:deoplete#auto_refresh_delay = 200
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:neoinclude#ctags_commands = 'tags'
let g:deoplete#disable_auto_complete = 0

call deoplete#custom#set('_', 'converters', ['converter_remove_paren'])
call deoplete#custom#set('_', 'matchers', ['matcher_fuzzy'])
g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['tag']
```

## The reproduce ways from neovim starting (Required!)

 1. open fugitive gitcommit buffer
 2. write commit message
 3. save and close `<esc>:x<cr>`

## Upload the log file
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/yevhen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 456, in on_event
[deoplete]     source.on_event(context)
[deoplete]   File "/Users/yevhen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py", line 27, in on_event
[deoplete]     self.__make_cache(context, bufnr)
[deoplete]   File "/Users/yevhen/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py", line 46, in __make_cache
[deoplete]     'filetype': self.vim.buffers[bufnr].options['filetype'],
[deoplete]   File "/Users/yevhen/.virtualenvs/neovim35/lib/python3.5/site-packages/neovim/api/nvim.py", line 375, in __getitem__
[deoplete]     raise KeyError(number)
[deoplete] KeyError: 10
[deoplete] Exception during buffer.on_event for event 'BufWritePost': 10.  Use :messages for error details.
```

**Comment by lsrdg** [comment]
Experiencing the same here, but it doesn't seem to be causing any trouble. Deoplete still rocks. ( :

**Comment by Shougo** [comment]
Dup of #479.

I am busy.
Please wait until fix the problem.
