### ISSUE TITLE
Exception during buffer.on_event for event 'Init': list index out of range.

### ISSUE THREAD

**Issue by ashb** [Shougo/deoplete.nvim#480]
# Problem summary

After 5-10s of this error appears in the status line. Nothing is done other than launching nvim

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/ash/etc/vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 456, in on_event
[deoplete]     source.on_event(context)
[deoplete]   File "/Users/ash/etc/vim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py", line 27, in on_event
[deoplete]     self.__make_cache(context, bufnr)
[deoplete]   File "/Users/ash/etc/vim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py", line 46, in __make_cache
[deoplete]     'filetype': self.vim.buffers[bufnr].options['filetype'],
[deoplete]   File "/Users/ash/.homebrew/lib/python3.5/site-packages/neovim/api/common.py", line 140, in __getitem__
[deoplete]     return self._fetch()[idx]
[deoplete] IndexError: list index out of range
[deoplete] Exception during buffer.on_event for event 'Init': list index out of range.  Use :messages for error details.
```

## Environment Information

 * deoplete version(SHA1): c202045

 * OS: OSX 10.12

 * neovim version: 0.2.0

 * `:CheckHealth` result(neovim ver.0.1.5-452+):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```

## minimal init.vim

```vim
let &runtimepath = &runtimepath . "," . expand('<sfile>:p:h')

call plug#begin('~/etc/vim/plugged')
" If I use this sha instead the error vanishes.
"Plug 'Shougo/deoplete.nvim', {'commit': '3ac8401', 'do': ':UpdateRemotePlugins'}
Plug 'Shougo/deoplete.nvim', {'commit': 'c202045', 'do': ':UpdateRemotePlugins'}
call plug#end()

let g:deoplete#enable_at_startup = 1

let g:deoplete#sources = {}
let g:deoplete#sources._ = ['buffer']
```

## The reproduce ways from neovim starting (Required!)

 1. start neovim
 2. wait 5-15 seconds
 3. 💥 

## logfile

[log_50089.txt](https://github.com/Shougo/deoplete.nvim/files/990547/log_50089.txt)

**Comment by Shougo** [comment]
Dup of https://github.com/Shougo/deoplete.nvim/issues/479
