### ISSUE TITLE
Too many errors from vim source make vim source disabled until neovim restart.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#518]
I use mater version, and when edit this vim file:
```vim
function! s:buffer_transient_state() abort
    let state = SpaceVim#api#import('transient_state') 
    call state.set_title('Buffer Selection Transient State')
    call state.defind_keys(
                \ {
                    \ 'layout' : 'vertical split',
                    \ 'left' : [
                        \ {
                        \ 'key' : {
                                \ 'name' : 'C-1 .. C-9',
                                \ 'pos' : [[1,4], [8,11]],
                                \ 'handles' : [
                                        \ ['' , ''],
                                        \ ],
                                \ },
                        \ 'desc' : 'goto nth window',
                        \ 'func' : '',
                        \ 'cmd' : '',
                        \ 'exit' : 0,
                        \ },
                    \ ],
                    \ 'right' : [
                        \ {
                        \ 'key' : 'n',
                        \ 'desc' : 'next buffer',
                        \ 'func' : '',
                        \ 'cmd' : 'bnext',
                        \ 'exit' : 0,
                        \ },
                        \ {
                        \ 'key' : ['N', 'p'],
                        \ 'desc' : 'previous buffer',
                        \ 'func' : '',
                        \ 'cmd' : 'bp',
                        \ 'exit' : 0,
                        \ },
                        \ {
                        \ 'key' : 'd',
                        \ 'desc' : 'kill buffer',
                        \ 'func' : '',
                        \ 'cmd' : 'call SpaceVim#mapping#close_current_buffer()',
                        \ 'exit' : 0,
                        \ },
                        \ {
                        \ 'key' : 'q',
                        \ 'desc' : 'quit',
                        \ 'func' : '',
                        \ 'cmd' : '',
                        \ 'exit' : 1,
                        \ },
                    \ ],
                \ }
                \ )
    call state.open()
endfunction
```
cursor is on line `                                \ 'pos' : [[1,4], [8,11]],`

I get too many errors:
```

[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 122, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/neco-vim/rplugin/python3/deoplete/sources/vim.py", line 29, in gather_candidates
[deoplete]     context['complete_str'])
[deoplete]   File "/home/wsdjeg/.local/lib/python3.6/site-packages/neovim/api/nvim.py", line 230, in call
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]   File "/home/wsdjeg/.local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/home/wsdjeg/.local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(let):E16: Invalid range'
[deoplete] Could not get completions from: vim.  Use :messages for error details.
1 change; before #81  12 seconds ago
```

I think this is error from https://github.com/Shougo/neco-vim

**Comment by Shougo** [comment]
It is neco-vim error.
Please update neco-vim.
