### ISSUE TITLE
deoplete errors require multiple <Enter> keypress

### ISSUE THREAD

**Issue by teto** [Shougo/deoplete.nvim#544]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Whenever there is an error (aka exception), one has to press <enter> for every line of the (long) traceback. It would be much better to see the whole error at once and press <Enter> only once.

For instance, I 've had to press at least 3 times <Enter> to go through this error; 
```
|| [deoplete] Traceback (most recent call last):
|| [deoplete]   File "/home/teto/.local/share/nvim/site/pack/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 467, in on_event
|| [deoplete]     source.on_event(context)
|| [deoplete]   File "/home/teto/.local/share/nvim/site/pack/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py", line 27, in on_event
|| [deoplete]     self.__make_cache(context, bufnr)
|| [deoplete]   File "/home/teto/.local/share/nvim/site/pack/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py", line 46, in __make_cache
|| [deoplete]     'filetype': self.vim.current.buffer.options['filetype'],
|| [deoplete]   File "/nix/store/fqwp1iq5af0y4l6xp9yv9z8al5m69nrm-python3-3.6.2-env/lib/python3.6/site-packages/neovim/api/common.py", line 81, in __getitem__
|| [deoplete]     return self._get(key)
|| [deoplete]   File "/nix/store/fqwp1iq5af0y4l6xp9yv9z8al5m69nrm-python3-3.6.2-env/lib/python3.6/site-packages/neovim/api/common.py", line 44, in request
|| [deoplete]     return self._session.request(name, self, *args, **kwargs)
|| [deoplete]   File "/nix/store/fqwp1iq5af0y4l6xp9yv9z8al5m69nrm-python3-3.6.2-env/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
|| [deoplete]     res = self._session.request(name, *args, **kwargs)
|| [deoplete]   File "/nix/store/fqwp1iq5af0y4l6xp9yv9z8al5m69nrm-python3-3.6.2-env/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
|| [deoplete]     raise self.error_wrapper(err)
|| [deoplete] neovim.api.nvim.NvimError: b'Invalid buffer id'
|| [deoplete] Exception during buffer.on_event for event 'Init': b'Invalid buffer id'.  Use :messages for error details.
```

## Expected
I expect to press <Enter> only once per error/trace.

## Environment Information

 * deoplete version(SHA1): 821d37530

 * OS: nixos

 * neovim version: VIM v0.2.1-dev                                                                           
Build type: Release

```
 * `:CheckHealth` result(neovim ver.0.1.5-452+):
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#deoplete_abook#check
========================================================================
## Dependencies
  - SUCCESS: Deoplete plugin is installed
  - ERROR: Addressbook file was not found
    - SUGGESTIONS:
      - help: deoplete_abook.txt

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/nix/store/macg539i39wpzxhysp1lmvv7zfx6nqsb-neovim-master/bin/nvim-python"
  - INFO: Executable: /nix/store/macg539i39wpzxhysp1lmvv7zfx6nqsb-neovim-master/bin/nvim-python
  - INFO: Python2 version: 2.7.13
  - INFO: nvim-python-neovim version: 0.1.13
  - SUCCESS: Latest nvim-python-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/nix/store/macg539i39wpzxhysp1lmvv7zfx6nqsb-neovim-master/bin/nvim-python3"
  - INFO: Executable: /nix/store/macg539i39wpzxhysp1lmvv7zfx6nqsb-neovim-master/bin/nvim-python3
  - INFO: Python3 version: 3.6.2
  - INFO: nvim-python3-neovim version: 0.1.13
  - SUCCESS: Latest nvim-python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - SUGGESTIONS:
      - Install Ruby and verify that `ruby` and `gem` commands work.
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

I am not especially interested in that specific error so I've skipped the reproduction part. This is true for any error. I can try to reproduce it if you are interested in it though.

**Comment by Shougo** [comment]
> Whenever there is an error (aka exception), one has to press for every line of the (long) traceback. It would be much better to see the whole error at once and press only once.

This is the feature.
So I just fix the error.

I don't know why the error is occurred.

**Comment by Shougo** [comment]
> Whenever there is an error (aka exception), one has to press for every line of the (long) traceback. It would be much better to see the whole error at once and press only once.

The error should not occurred.  Not just skip keypressing problem.
