### ISSUE TITLE
Feature Request: Configure max length for types

### ISSUE THREAD

**Issue by kennykaye** [Shougo/deoplete.nvim#558]
Feature request:

**Observed behavior**
When rendering a completion with long type declarations, the full declaration is displayed (despite `deoplete#max_menu_width` setting).

**Desired behavior**
The user is able to configure the max_width of the types in a similar manner to `deoplete#max_abbr_width`. The result would be the type declarations greater in length than the configured maximum would be truncated to the specified length.

<img width="1425" alt="screen shot 2017-10-21 at 7 51 16 am" src="https://user-images.githubusercontent.com/3267574/31853007-69fb2ba8-b636-11e7-8078-70416917b55c.png">

**Current Configuration**
```viml
" Relevant plugins
Plug 'Shougo/deoplete.nvim',              { 'do': ':UpdateRemotePlugins' }
Plug 'carlitux/deoplete-ternjs',          { 'for': ['javascript', 'javascript.jsx'] }
Plug 'zchee/deoplete-go',                 { 'do': 'make'}
Plug 'ternjs/tern_for_vim',               { 'for': ['javascript', 'javascript.jsx'] }

" ...

" Use deoplete.
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#sources = {}
let g:deoplete#sources['javascript.jsx'] = ['file', 'tern']
let g:deoplete#sources['css'] = []
let g:deoplete#max_abbr_width = 30
let g:deoplete#max_menu_width = 40

" Use tern_for_vim.
let g:tern#command = ["tern"]
let g:tern#arguments = ["--persistent"]

let g:deoplete#omni#functions = {}
let g:deoplete#omni#functions.javascript = [
\ 'tern#Complete',
\ 'jspc#omni'
\ ]

let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'

let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.css='\w\+'

let b:deoplete_ignore_sources = ['buffer']

"Add extra filetypes
let g:deoplete#sources#ternjs#filetypes = [
\ 'jsx',
\ 'javascript',
\ 'javascript.jsx',
\ ]

let g:deoplete#sources#ternjs#docs = 1
let g:deoplete#sources#ternjs#types = 1
let g:deoplete#sources#ternjs#include_keywords = 1
```

**Comment by Shougo** [comment]
The feature is already implemented by `converter_truncate_abbr`.

Please check your filters configurations in deoplete-ternjs.

**Comment by Shougo** [comment]
I have read the source code.
But it does not overwrite the configuration.
https://github.com/carlitux/deoplete-ternjs/blob/master/rplugin/python3/deoplete/sources/ternjs.py

**Comment by Shougo** [comment]
Ah, I get it.
It is kind instead "abbr" or "menu".

**Comment by Shougo** [comment]
Implemented.

**Comment by kennykaye** [comment]
@Shougo Your turnaround time is incredible, thank you!

**Comment by kennykaye** [comment]
@Shougo Heads up, I'm seeing this exception when performing a completion on a value with no type.

```
Parsing error: Unexpected token
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/Kenny/Development/dotfiles/vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 224, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/Kenny/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_kind.py", line 28, in filter
[deoplete]     max_width, '..', footer_width)
[deoplete]   File "/Users/Kenny/Development/dotfiles/vim/bundle/deoplete.nvim/rplugin/python3/deoplete/util.py", line 192, in truncate_skipping
[deoplete]     if len(string) <= max_width/2:
[deoplete] TypeError: object of type 'NoneType' has no len()
[deoplete] Could not filter using: <deoplete.filter.converter_truncate_kind.Filter object at 0x103669a58>.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/Kenny/Development/dotfiles/vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 224, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/Kenny/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_kind.py", line 28, in filter
[deoplete]     max_width, '..', footer_width)
[deoplete]   File "/Users/Kenny/Development/dotfiles/vim/bundle/deoplete.nvim/rplugin/python3/deoplete/util.py", line 192, in truncate_skipping
[deoplete]     if len(string) <= max_width/2:
[deoplete] TypeError: object of type 'NoneType' has no len()
```

**Comment by Shougo** [comment]
deoplete-ternjs is broken.
https://github.com/carlitux/deoplete-ternjs/blob/master/rplugin/python3/deoplete/sources/ternjs.py#L325
It must be:

```
icon = rec.get('type', '')
```

But OK.  I have fixed.
