### ISSUE TITLE
Errors with Python 3

### ISSUE THREAD

**Issue by mhartington** [Shougo/deoplete.nvim#59]
Getting some errors in the latest release.

```
Error detected while processing function deoplete#init#enable..remote#define#CommandBootstrap:
line    5:
Exception('no request handler registered for "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete.py:command:DeopleteInitializePython"',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python3.5/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/host.py", line 62, in _on_request
    raise Exception(msg)
Exception: no request handler registered for "/Users/mhartington/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete.py:command:DeopleteInitializePython"
Error detected while processing function deoplete#init#enable..remote#define#CommandBootstrap:
line    5:
Error detected while processing function <SNR>261_completion_begin:
line    1:
E121: Undefined variable: g:deoplete#_channel_id
Error detected while processing function <SNR>261_completion_begin:
line    1:
E116: Invalid arguments for function rpcnotify
```

What more information do you need from me

**Comment by Shougo** [comment]
Please read the documentation.

```
Q: deoplete does not work...

A: Please check followings.

  1. Please update neovim to latest version.

  2. Please update neovim python3 module to latest version.
>
	$ sudo pip3 install neovim --upgrade
<
  3. Please execute |:UpdateRemotePlugins| command manually.

  4. Please check if Python3 interface works.  You can check it by ":echo
  has('python3')" command.

https://github.com/neovim/neovim/wiki/Troubleshooting#python-support-isnt-working
```

I think your neovim python3 library and neovim binary are too old.

**Comment by mhartington** [comment]
Updated both and still get the errors

**Comment by Shougo** [comment]
Really?
Please upload the log file.

**Comment by Shougo** [comment]
Current master neovim-python is 0.0.38.
Please upload your neovim-python's version.

**Comment by mhartington** [comment]
Hmmm, more digging, seems there's a conflict with another plugin. I can't replicate it with a minimal vimrc, so I'll close this for now and report back when I find out whats the conflict. Sorry for the noise!

**Comment by Shougo** [comment]
OK.

**Comment by RenatoUtsch** [comment]
Just as an update, it seems that installing deoplete on a place that is not `~/.vim/plugged` causes this error. This happened when I changed the plugins directory to `~/.config/nvim/plugged`.
