### ISSUE TITLE
Error in Rust completion (racer)

### ISSUE THREAD

**Issue by antoyo** [Shougo/deoplete.nvim#61]
Hello.
I get the following errors with Rust completion (`racer`):

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "~/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 83, in completion_begin
[deoplete]     context)
[deoplete]   File "~/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 96, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "~/.nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 148, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "~/.nvim/plugged/racer/rplugin/python3/deoplete/sources/racer.py", line 75, in gather_candidates
[deoplete]     if int(self.vim.eval('g:racer_insert_paren')):
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/api/nvim.py", line 127, in eval
[deoplete]     return self._session.request('vim_eval', string, async=async)
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/api/common.py", line 230, in request
[deoplete]     return walk(self._in, self._session.request(name, *args, **kwargs),
[deoplete]   File "/usr/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 90, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Failed to evaluate expression'
[deoplete] An error has occurred. Please execute :messages command.
```

This should prints the functions from the module instead.

Here is how to reproduce this issue:

* Open nvim with a rust file (`nvim test.rs`).
* Type `use std::env::`.
* Execute the `:messages` command to see the error.

I've updated neovim and the python plugins just now.

Here is my config:

```vim
" Deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1

" Racer
let g:racer_cmd = "/usr/bin/racer"
let $RUST_SRC_PATH = "/usr/src/rust/src/"
```

OS: ArchLinux
Neovim version: NVIM 0.0.0-alpha+201510231011 (compiled Oct 24 2015 15:57:08)

It should be noted that typing:

```rust
use std::env::A
```

shows the results.

It also works fine in other module (for instance, `std::num`).

Thanks to fix this issue.

**Comment by Shougo** [comment]
I have reproduced it.
You must set `g:racer_insert_paren` variable.
Recommend is to install vim-racer plugin.
I will request deoplete source into vim-racer plugin.
