### ISSUE TITLE
unexpected error occurred 

### ISSUE THREAD

**Issue by icearith** [Shougo/deoplete.nvim#639]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
when I type `import ` in a python file while typing the space, an error raised.

![screen shot 2018-02-07 at 3 28 40 pm](https://user-images.githubusercontent.com/2555093/35904047-a3fcb3d0-0c1c-11e8-99ed-5674e90d84fe.png)

## Environment Information

 * deoplete version(SHA1): 

 * OS: macOS 10.13.3 (17D47)

 * neovim/Vim version: NVIM v0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python2.7"
  - INFO: Executable: /usr/local/bin/python2.7
  - INFO: Python2 version: 2.7.14
  - INFO: python2.7-neovim version: 0.2.1
  - OK: Latest python2.7-neovim is installed: 0.2.1

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.1
  - OK: Latest python3-neovim is installed: 0.2.1

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - ERROR: Command error (job=25): /usr/local/bin/neovim-ruby-host --version
    Output: /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem neovim (>= 0.a) with executable neovim-ruby-host (Gem::GemNotFoundException)	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'	from /usr/local/bin/neovim-ruby-host:23:in `<main>'
  - ERROR: Failed to run: /usr/local/bin/neovim-ruby-host --version
    - ADVICE:
      - Report this issue with the output of: 
      - /usr/local/bin/neovim-ruby-host --version

## Node provider (optional)
  - INFO: Node: v9.5.0
  - INFO: Host: /usr/local/bin/neovim-node-host
  - WARNING: Package "neovim" is out-of-date. Installed: 3.5.0, latest: 3.5.2
    - ADVICE:
      - Run in shell: npm update neovim


```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1


I use pure Spacevim
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file

**Comment by Shougo** [comment]
https://github.com/SpaceVim/SpaceVim/issues/1382#issuecomment-363677185

Please check your configuration or SpaceVim.

**Comment by Shougo** [comment]
> I use pure Spacevim

It is SpaceVim error.
Please wait until it is fixed in SpaceVim.
