### ISSUE TITLE
Recent changes broke Julia support

### ISSUE THREAD

**Issue by tbole** [Shougo/deoplete.nvim#647]
# Problems summary

Deoplete throws errors when opening Julia files and completion fails. Other languages such as Python, C or Fortran are not affected, I have not made too many tests though. This only happens with more recent deoplete versions. The last working version was 4.0-serial. After the merge of 0a6debfe73a9cc6deb423bd50dbdd3ded1992567 autocompletion fails, but no errors occur.  At 60bfdaabc9e8a9570a44ac14d944ce3f1a4abfaa (or earlier) errors are raised.

[deoplete] Traceback (most recent call last):                                                                                                                                                                 
[deoplete]   File "/home/tbole/.vim/dein/.cache/init.vim/.dein/rplugin/python3/deoplete/dp_main.py", line 37, in main                                                                                       
[deoplete]     child.main()                                                                                                                                                                                   
[deoplete]   File "/home/tbole/.vim/dein/.cache/init.vim/.dein/rplugin/python3/deoplete/child.py", line 58, in main                                                                                         
[deoplete]     self._unpacker.feed(feed)                                                                                                                                                                      
[deoplete]   File "msgpack/_unpacker.pyx", line 402, in msgpack._unpacker.Unpacker.feed                                                                                                                       
[deoplete]   File "msgpack/_unpacker.pyx", line 152, in msgpack._unpacker.get_data_from_buffer                                                                                                                
[deoplete] TypeError: a bytes-like object is required, not 'NoneType'

## Expected

No errors, autocompletion works.

## Environment Information

 * deoplete version(SHA1): 0a6debfe73a9cc6deb423bd50dbdd3ded1992567 and later

 * OS: Ubuntu 17.10

 * neovim/Vim version: nvim v0.2.3-dev

 * `:checkhealth` or `:CheckHealth` result(neovim only):
    
    health#deoplete#check
    ========================================================================
    ## deoplete.nvim
      - OK: has("nvim") was successful
      - OK: has("python3") was successful
      - INFO: If you're still having problems, try the following commands:
        $ export NVIM_PYTHON_LOG_FILE=/tmp/log
        $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
        $ nvim
        $ cat /tmp/log_{PID}
        and then create an issue on github
    
    health#nvim#check
    ========================================================================
    ## Configuration
      - OK: no issues found
    
    ## Performance
      - OK: Build type: RelWithDebInfo
    
    ## Remote Plugins
      - OK: Up to date
    
    ## terminal
      - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
      - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
      - INFO: $COLORTERM='truecolor'
    
    health#provider#check
    ========================================================================
    ## Clipboard (optional)
      - OK: Clipboard tool found: xsel
    
    ## Python 2 provider (optional)
      - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
      - INFO: Executable: /usr/bin/python2
      - INFO: Python2 version: 2.7.14
      - INFO: python2-neovim version: 0.2.1
      - OK: Latest python2-neovim is installed: 0.2.1
    
    ## Python 3 provider (optional)
      - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
      - INFO: Executable: /usr/bin/python3
      - INFO: Python3 version: 3.6.3
      - INFO: python3-neovim version: 0.2.1
      - OK: Latest python3-neovim is installed: 0.2.1
    
    ## Ruby provider (optional)
      - INFO: Ruby: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
      - INFO: Host: /usr/bin/neovim-ruby-host
      - WARNING: Gem "neovim" is out-of-date. Installed: 0.3.1, latest: 0.6.2
        - ADVICE:
          - Run in shell: gem update neovim
    
    ## Node.js provider (optional)
      - WARNING: `node` and `npm` must be in $PATH.
        - ADVICE:
          - Install Node.js and verify that `node` and `npm` commands work.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim
let g:deoplete#enable_at_startup = 1
if dein#load_state(expand('~/.vim/dein'))
    call dein#begin(expand('~/.vim/dein'))
    call dein#add('Shougo/dein.vim')
    call dein#add('Shougo/deoplete.nvim')
    call dein#add('JuliaEditorSupport/deoplete-julia')
    call dein#end()
    call dein#save_state()
endif
let g:default_julia_version = "0.6"  "enter Julia version here, use devel for latest
```

## The log

[deoplete.log](https://github.com/Shougo/deoplete.nvim/files/1706159/deoplete.log)

## The reproduce ways from neovim/Vim starting (Required!)

 1. Install Julia and Julia plugin for deoplete
 2. Open arbitrary Julia source [file ](https://github.com/JuliaParallel/MPI.jl/blob/master/src/MPI.jl)

**Comment by Shougo** [comment]
I will test it later.

**Comment by Shougo** [comment]
Reproduced the problem.

**Comment by Shougo** [comment]
```vim
diff --git a/rplugin/python3/deoplete/child.py b/rplugin/python3/deoplete/child.py
index e2308f7..2982e2c 100644
--- a/rplugin/python3/deoplete/child.py
+++ b/rplugin/python3/deoplete/child.py
@@ -51,6 +51,9 @@ class Child(logger.LoggingMixin):
     def main(self):
         while True:
             feed = sys.stdin.buffer.raw.read(102400)
+            if feed is None:
+                continue
+
             if feed == b'':
                 # EOF
                 return
```

It fixes the problem.

**Comment by tbole** [comment]
Thanks a lot for the quick fix, now everything seems to work fine! Is this going to land in master soon?

**Comment by Shougo** [comment]
> Sorry, this was a bit too quick. While all completion features work well, the deoplete process is constantly running at 100% CPU, even if there's no activity in nvim.

deoplete-julia implementation is not good well.
It generates tags file and it is heavy work.

**Comment by Shougo** [comment]
https://github.com/JuliaEditorSupport/deoplete-julia/blob/master/rplugin/python3/deoplete/sources/julia.py#L86

make caching is works after you have changed file.
