### ISSUE TITLE
Deoplete throwing Broken pipe errors in insert mode

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/deoplete.nvim#649]
# Problems summary
Deoplete throws Broken pipe errors when entering insert mode:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/sochan/dotfiles/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 63, in completion_begin
[deoplete]     is_async, position, candidates = self.merge_results(context)                                                                   
[deoplete]   File "/home/sochan/dotfiles/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 110, in merge_results
[deoplete]     result = parent.merge_results(context)                                                                                       
[deoplete]   File "/home/sochan/dotfiles/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 47, in merge_results
[deoplete]     queue_id = self._put('merge_results', [context])                                                                          
[deoplete]   File "/home/sochan/dotfiles/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 88, in _put
[deoplete]     self._proc.write({'name': name, 'args': args, 'queue_id': queue_id})                                             
[deoplete]   File "/home/sochan/dotfiles/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/process.py", line 75, in write
[deoplete]     self._proc.stdin.flush()                                                                                           
[deoplete] BrokenPipeError: [Errno 32] Broken pipe
[deoplete] Error while gathering completions.  Use :messages for error details.
```
I assume this has something to do with how the python process running `neovim` server starts and hangs, but I have no idea how to debug this, and if it in fact has anything to do with Deoplete. But it seems to be triggered by it and no other plugin.

## Expected
Working completion.

## Environment Information

 * deoplete version(SHA1): c5f8165245a1bd0a9a9f3d167ec855994fcd1e14
 * OS: Debian Testing
 * neovim/Vim version: `v0.2.2`
 * `:CheckHealth`:
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.2.1
  - OK: Latest python2-neovim is installed: 0.2.1

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.1
  - OK: Latest python3-neovim is installed: 0.2.1
```

## Minimal init.vim
```vim
set runtimepath+=/home/sochan/.config/nvim/bundle/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)
 1. `vim -u test.vim`
 2. Enter insert mode
 3. See errors

## Screen shot (if possible)
![deoplete_err](https://user-images.githubusercontent.com/2212681/35976859-aaab2566-0ce1-11e8-9f93-8dafcacd6e90.png)

## Upload the log file
[nvim.log](https://github.com/Shougo/deoplete.nvim/files/1707284/nvim.log)

**Comment by Shougo** [comment]
Please test the latest version of deoplete.

And please see the issue.
https://github.com/Shougo/deoplete.nvim/issues/646

**Comment by PonderingGrower** [comment]
Just tested it, seems to be working fine now. Thanks for an amazingly fast fix Shougo!

**Comment by Shougo** [comment]
OK.
