### ISSUE TITLE
BrokenPipeError [Errno 32] on insert and quit

### ISSUE THREAD

**Issue by IndicaInkwell** [Shougo/deoplete.nvim#653]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Emits a broken pipe error on insert, while typing in insert, and when quitting nvim. Error is emitted every keystroke.

## Expected
To enter insert mode and receive completions.

## Environment Information

 * deoplete version(SHA1): fd5e562

 * OS: macOS Sierra 10.12.6

 * neovim/Vim version: neovim v0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

\#\# deoplete.nvim
  \- OK: has("nvim") was successful
  \- OK: has("python3") was successful

# Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Startup nvim
 2. In normal mode press i
 3. See error messages fill up command line
 4. quit
 5. See error output in terminal after quitting

### On Insert

Traceback (most recent call last):
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 65, in completion_begin
    is_async, position, candidates = self.merge_results(context)
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 112, in merge_results
    result = parent.merge_results(context)
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 51, in merge_results
    queue_id = self._put('merge_results', [context])
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 94, in _put
    'name': name, 'args': args, 'queue_id': queue_id
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/process.py", line 73, in write
    self._proc.stdin.write(self._packer.pack(expr))
BrokenPipeError: [Errno 32] Broken pipe
Error while gathering completions.  Use :messages for error details.

  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 44, in on_event
    self._deoplete.on_event(context)

  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 206, in on_event
    parent.on_event(context)

  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 67, in on_event
    self._put('on_event', [context])

  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 94, in _put
    'name': name, 'args': args, 'queue_id': queue_id

  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/process.py", line 73, in write
    self._proc.stdin.write(self._packer.pack(expr))

BrokenPipeError: [Errno 32] Broken pipe

### On Quit

Traceback (most recent call last):
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 44, in on_event
    self._deoplete.on_event(context)
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 206, in on_event
    parent.on_event(context)
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 67, in on_event
    self._put('on_event', [context])
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 94, in _put
    'name': name, 'args': args, 'queue_id': queue_id
  File "/Users/me/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/process.py", line 74, in write
    self._proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe<Paste>

**Comment by IndicaInkwell** [comment]
I will look into this and see what I can find out and help with tomorrow.

**Comment by Shougo** [comment]
Please see the issues.
https://github.com/Shougo/deoplete.nvim/issues/649
https://github.com/Shougo/deoplete.nvim/issues/646
https://github.com/Shougo/deoplete.nvim/issues/635#issuecomment-363331278

**Comment by IndicaInkwell** [comment]
After restarting my computer, I cannot reproduce the error. I don't think this a deoplete issue anymore but I don't know how to debug this for confirmation.

Additional details about environment:
- neovim and python-client are up to date
- NVIM_LISTEN_ADDRESS has not been set

Let me know if there's anything I can do to help.

**Comment by blueyed** [comment]
@IndicaInkwell 
Are you using deoplete-jedi?  There is an issue reported for it that would cause this at https://github.com/zchee/deoplete-jedi/issues/152.
In general it might happen if a source crashes, and it would be useful to have the full deoplete log then.

**Comment by IndicaInkwell** [comment]
@blueyed I am and I believe I was writing in python when the error first occurred too. I have yet to reproduce the error but if it happens again I'll be sure to get the full log.

Oh, the error did continue even with just the minimal vimrc posted above, though.

**Comment by Shougo** [comment]
Please use the latest version of deoplete.
The latest version prints more detailed log.

**Comment by FelipeMarcelino** [comment]
Same here!!!

**Comment by Shougo** [comment]
> Please use the latest version of deoplete.
> The latest version prints more detailed log.

We have no ESP skills
