### ISSUE TITLE
Unintended decrement on dot-repeat

### ISSUE THREAD

**Issue by iTakeshi** [Shougo/deoplete.nvim#696]
# Problems summary
When using `.` (dot-repeat), if there is a number just after the location where the dot-repeat is executed, that number is unintentionally decremented.
This phenomenon seems to occur only when the current file-type is `xml`.

## Expected
No unintentional decrement.

## Environment Information

 * deoplete version(SHA1): HEAD of `master` on 2017/Mar/21 (8e39cfd)

 * OS: Arch Linux / ubuntu 16.04 & 18.04

 * neovim/Vim version: NVIM v0.2.2 (also confirmed on nightly on 2017/Mar/21: neovim/neovim@739fb93)

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.2.4
  - OK: Latest python2-neovim is installed: 0.2.4

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.4
  - OK: Latest python3-neovim is installed: 0.2.4

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Node provider (optional)
  - INFO: Node: v9.8.0
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

```sh
$ ls
deoplete.nvim/  init.vim  nvim.appimage  test.xml
$ cat init.vim 
set runtimepath+=~/deop_test/deoplete.nvim
let g:deoplete#enable_at_startup = 1
$ cat test.xml 
<tag attr="1"/>
<tag attr="1"/>
$ ./nvim.appimage -u init.vim test.xml
```

1. move the cursor onto the word "attr" on line 1
2. `ciw` -> `hoge` -> Esc
3. move the cursor onto the word "attr" on line 2
4. press `.` (repeat the previous operation)
5. the number `1` on line 2 is decremented to `0`, and the cursor jumps to anywhere (the location varies for each trial)

## Screen shot (if possible)
![simplescreenrecorder-2018-03-21_12 19 48](https://user-images.githubusercontent.com/1460175/37693569-e2743ea0-2d03-11e8-9675-8470f738406f.gif)

## Upload the log file
```
2018-03-21 12:10:51,227 [ERROR @ base_events.py:default_exception_handler:1265] 10839 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/lib/python3.6/asyncio/base_events.py:1166> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached',)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1191, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 858, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2018-03-21 12:10:51,228 [ERROR @ base_events.py:default_exception_handler:1265] 10839 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/lib/python3.6/asyncio/base_events.py:1166> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached',)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1191, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 858, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2018-03-21 12:10:51,228 [ERROR @ base_events.py:default_exception_handler:1265] 10839 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/lib/python3.6/asyncio/base_events.py:1166> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached',)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1191, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 858, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2018-03-21 12:10:51,229 [ERROR @ base_events.py:default_exception_handler:1265] 10839 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/lib/python3.6/asyncio/base_events.py:1166> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached',)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1191, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 858, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
```

**Comment by Shougo** [comment]
It seems `.` bug in Vim.
It is also reproduced in Vim8.

**Comment by iTakeshi** [comment]
I see, but when I remove deoplete (i.e. `nvim -u NONE`), this phenomenon doesn't happen.
So even if this actually is a bug in vim/neovim, I think that deoplete "triggers" this behavior.
Do you have any ideas?

**Comment by Shougo** [comment]
It can be reproduced without deoplete.
I will create the example.
Please wait.

**Comment by Shougo** [comment]
Here.

```vim
autocmd InsertEnter * call feedkeys("\<C-x>\<C-o>", 'in')
```

It is easy to reproduce.
It should be reported in Vim issues.

**Comment by iTakeshi** [comment]
It reproduced the problem in vanilla neovim. Thank you.
