### ISSUE TITLE
Remove duplicates if dup source

### ISSUE THREAD

**Issue by Shougo** [Shougo/deoplete.nvim#705]
```diff
diff --git a/rplugin/python3/deoplete/child.py b/rplugin/python3/deoplete/child.py
index 6261870..4da3631 100644
--- a/rplugin/python3/deoplete/child.py
+++ b/rplugin/python3/deoplete/child.py
@@ -157,16 +157,20 @@ class Child(logger.LoggingMixin):
         merged_results = []
         for result in [x for x in results
                        if not self._is_skip(x['context'], x['source'])]:
-            source_result = self._source_result(result, context['input'])
-            if source_result:
+            if self._update_result(result, context['input']):
                 rank = get_custom(self._custom,
                                   result['source'].name, 'rank',
                                   result['source'].rank)
+                dup = bool(result['source'].filetypes)
+                candidates = result['candidates']
+                if dup:
+                    # Remove duplicates
+                    candidates = sorted(set(candidates), key=candidates.index)
                 merged_results.append({
-                    'complete_position': source_result['complete_position'],
+                    'complete_position': result['complete_position'],
                     'mark': result['source'].mark,
-                    'dup': bool(result['source'].filetypes),
-                    'candidates': result['candidates'],
+                    'dup': dup,
+                    'candidates': candidates,
                     'source_name': result['source'].name,
                     'rank': rank,
                 })
@@ -302,7 +306,7 @@ class Child(logger.LoggingMixin):
         except Exception:
             error_tb(self._vim, 'Errors from: %s' % f)

-    def _source_result(self, result, context_input):
+    def _update_result(self, result, context_input):
         source = result['source']

         # Gather async results
```

**Comment by EdmundsEcho** [comment]
Hi Shougo,  Before asking you this, I have googled and even emailed github support before asking you this...  How do I apply this patch?  I could not download a file from this link.

**Comment by Shougo** [comment]
@EdmundsEcho 

`$ cd ~/deoplete.nvim`
`$  vim patch.diff`
`$ patch -p1 <./patch.diff`

**Comment by EdmundsEcho** [comment]
Thank you.  I applied the patch thanks to your additional help (I will be adding that to my `sys admin` notes).

When I triggered `deoplete` I received the following error messages:

```
"src/PreRender.hs" 96L, 2753C
Success finding hscope.out
[deoplete] Traceback (most recent call last):
  File "/Users/edmund/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/dp_main.py", line 52, in main
    child.main_loop(stdout)
  File "/Users/edmund/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 69, in main_loop
    ret = self.main(name, args, queue_id)
  File "/Users/edmund/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 90, in main
    ret = self._merge_results(args[0], queue_id)
  File "/Users/edmund/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 168, in _merge_results
    candidates = sorted(set(candidates), key=candidates.index)
TypeError: unhashable type: 'dict'
Error in child.  Use :messages / see above for error details.
[deoplete] Traceback (most recent call last):
  File "/Users/edmund/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/dp_main.py", line 52, in main
    child.main_loop(stdout)
  File "/Users/edmund/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 69, in main_loop
    ret = self.main(name, args, queue_id)
  File "/Users/edmund/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 90, in main
    ret = self._merge_results(args[0], queue_id)
  File "/Users/edmund/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 168, in _merge_results
    candidates = sorted(set(candidates), key=candidates.index)
TypeError: unhashable type: 'dict'
Error in child.  Use :messages / see above for error details.

Error: Parse error. Found:     > ( [cartesian product of all comps for each ReqRange] )  -}> :  -- TODO: Measurement MeasType [Component] [Range]  -- data Measurement b r = Measurement MeasType (Components b) (Range r) Why not: null
```
My NVim `CheckHealth` reports all `OK`.  I'm using the latest versions of Python 2, 3 and Ruby.

**Comment by mr-tabasco** [comment]
Following an update I'm experiencing the same issue as @EdmundsEcho.

Error details:

```
[deoplete] Traceback (most recent call last):
  File "/home/mhahe/projects/mhahe/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/dp_main.py", line 52, in main
    child.main_loop(stdout)
  File "/home/mhahe/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 69, in main_loop
    ret = self.main(name, args, queue_id)
  File "/home/mhahe/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 90, in main
    ret = self._merge_results(args[0], queue_id)
  File "/home/mhahe/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 168, in _merge_results
    candidates = sorted(set(candidates), key=candidates.index)
TypeError: unhashable type: 'dict'
Error in child.  Use :messages / see above for error details.
```

**Comment by Shougo** [comment]
The patch is broken.

Another solution is needed.

**Comment by Shougo** [comment]
@EdmundsEcho @mr-tabasco https://github.com/Shougo/deoplete.nvim/issues/706

**Comment by Shougo** [comment]
@EdmundsEcho 

Please test the patch instead.

```diff
diff --git a/rplugin/python3/deoplete/child.py b/rplugin/python3/deoplete/child.py
index 6f02917..6bd7d01 100644
--- a/rplugin/python3/deoplete/child.py
+++ b/rplugin/python3/deoplete/child.py
@@ -11,7 +11,7 @@ import sys
 import time
 import msgpack

-from collections import defaultdict
+from collections import defaultdict, OrderedDict

 import deoplete.source  # noqa
 import deoplete.filter  # noqa
@@ -164,9 +164,10 @@ class Child(logger.LoggingMixin):
                 dup = bool(result['source'].filetypes)
                 candidates = result['candidates']
                 # Note: cannot use set() for dict
-                # if dup:
-                #     # Remove duplicates
-                #     candidates = sorted(set(candidates), key=candidates.index)
+                if dup:
+                    # Remove duplicates
+                    candidates = list(OrderedDict(
+                        (id(d), d) for d in candidates).values())
                 merged_results.append({
                     'complete_position': result['complete_position'],
                     'mark': result['source'].mark,
```

**Comment by EdmundsEcho** [comment]
The patch did not fully load (see below).  So, I also pulled a version of the full file and tested it.  I could not confirm whether I had the most recent version.  This said, the update did not generate errors in nvim per se, but I still see duplicates.

```
patching file rplugin/python3/deoplete/child.py
Hunk #2 FAILED at 164.
1 out of 2 hunks FAILED -- saving rejects to file rplugin/python3/deoplete/child.py.rej
patching file rplugin/python3/deoplete/util.py
patching file test/rplugin/python3/deoplete/test_util.py
```

**Comment by Shougo** [comment]
> patching file rplugin/python3/deoplete/child.py
> Hunk #2 FAILED at 164.
> 1 out of 2 hunks FAILED -- saving rejects to file rplugin/python3/deoplete/child.py.rej

The patching is failed in child.py.  Please change the code manually.

**Comment by Shougo** [comment]
> The patch did not fully load (see below). So, I also pulled a version of the full file and tested it. I could not confirm whether I had the most recent version. This said, the update did not generate errors in nvim per se, but I still see duplicates.

Please confirm the patched version.
To confirm: `git log` result is the latest commit?
`git diff` is same with my patch?

**Comment by EdmundsEcho** [comment]
output from git log:
```
patching file rplugin/python3/deoplete/child.py
Hunk #2 FAILED at 164.
1 out of 2 hunks FAILED -- saving rejects to file rplugin/python3/deoplete/child.py.rej
commit d8da6ebf0630639ce1139d7614f6da437aa0a919 (HEAD -> master, origin/master, origin/HEAD)
Author: Shougo Matsushita <Shougo.Matsu@gmail.com>
Date:   Wed Mar 21 17:44:30 2018 +0900

    Fix #695 file.py initialization

commit 2a3ce9432be95fdd4bf368b3d95c6d226553658f
Author: Shougo Matsushita <Shougo.Matsu@gmail.com>
Date:   Wed Mar 21 17:21:10 2018 +0900

    Fix #692 Event loop is closed issue
```

I updated the `patch.diff` file with the latest (64 lines long, with index ending in 100644).  I ran the patch in the root `deoplete.nvim` directory (i.e., _not_ in the `rplugin/python3.../deoplete/`)

I will make the changes manually tomorrow morning.

**Comment by Shougo** [comment]
I think your deoplete is not the latest version.

**Comment by Shougo** [comment]
Because, "Fix #695 file.py initialization" is:

https://github.com/Shougo/deoplete.nvim/commit/d8da6ebf0630639ce1139d7614f6da437aa0a919

Wow, too old.

**Comment by EdmundsEcho** [comment]
A 7 day old master in Shougo update years, is equivalent to a very long time 👍 

```
commit 9e92ab4575cf3f854bce82e8ad85f306af908dba (HEAD -> master)
Merge: d8da6eb 2437d59
Author: Edmund Cape <edmund.cape@lucivia.com>
Date:   Wed Mar 28 06:39:59 2018 -0400

    Merge branch 'master' of https://github.com/Shougo/deoplete.nvim

commit 2437d5924a107f7adebedf2f7c1ad5d4c5551c59 (origin/master, origin/HEAD)
Author: Shougo Matsushita <Shougo.Matsu@gmail.com>
Date:   Wed Mar 28 08:00:00 2018 +0900

    Fix #706 set() error
```
I pulled the latest master and applied the patch.  The patch installed easily. However, I still see duplicates...

**Comment by Shougo** [comment]
Implemented.

> I pulled the latest master and applied the patch. The patch installed easily. However, I still see duplicates...

Really?  I need to test the problem.
I think it is not real duplicated.

**Comment by Shougo** [comment]
Please test the latest version.

**Comment by Shougo** [comment]
Note:  It must be reproduce able.
If not, I will ignore your issue.
Sorry.

**Comment by EdmundsEcho** [comment]
I understand.  I will spend more time on it over the weekend.

**Comment by Shougo** [comment]
OK
