### ISSUE TITLE
Deoplete Error

### ISSUE THREAD

**Issue by ihexon** [Shougo/deoplete.nvim#706]
Deoplete output error after I update latest(the commit `Fix handler event`)
[SpaceVim: can not use `<C-N><C-P>`](https://github.com/SpaceVim/SpaceVim/issues/1558)

```
[deoplete] Traceback (most recent call last):                                                                                                                                                                        
  File "/home/zhuzhihao/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/dp_main.py", line 52, in main                                                                                 
    child.main_loop(stdout)                                                                                                                                                                                          
  File "/home/zhuzhihao/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/child.py", line 69, in main_loop                                                                              
    ret = self.main(name, args, queue_id)                                                                                                                                                                            
  File "/home/zhuzhihao/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/child.py", line 90, in main                                                                                   
    ret = self._merge_results(args[0], queue_id)                                                                                                                                                                     
  File "/home/zhuzhihao/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/child.py", line 168, in _merge_results                                                                        
    candidates = sorted(set(candidates), key=candidates.index)                                                                                                                                                       
TypeError: unhashable type: 'dict'                                                                                                                                                                                   
Error in child.  Use :messages / see above for error details.
```

## Environment Information

 * deoplete version(SHA1):
`commit 2a52282a519b306ade792630e7012306110d96de (HEAD -> master, origin/master, origin/HEAD)`

 * OS: ArchLinux

 * neovim/Vim version:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by apiarian** [comment]
I saw the same issue on my mac. Git bisect tells me that the first bad commit was d2fe09db5f1093df2ddb5d884457ec8d45844240
