### ISSUE TITLE
Exception during buffer.on_event for event 'BufReadPost': bad character range \w-0 at position 10.

### ISSUE THREAD

**Issue by ipod825** [Shougo/deoplete.nvim#830]
# Problems summary
re module fails for a specific filetype.

## Environment Information

 * deoplete version (SHA1):
4.0

 * OS:
Linux

 * neovim/Vim `:version` output:
NVIM v0.2.0

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: exists("v:t_list") was successful
  - SUCCESS: has("timers") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/local/google/home/smwang/.pyenv/versions/neovim2/bin/python"
  - WARNING: Your virtualenv is not set up optimally.
    - SUGGESTIONS:
      - Create a virtualenv specifically for Neovim and use `g:python_host_prog`.  This will avoid the need to install Neovim's Python module in each virtualenv.
  - INFO: Executable: /usr/local/google/home/smwang/.pyenv/versions/neovim2/bin/python
  - INFO: Python2 version: 2.7.15
  - INFO: python-neovim version: 0.2.6
  - SUCCESS: Latest python-neovim is installed: 0.2.6

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/google/home/smwang/.pyenv/versions/neovim3/bin/python"
  - WARNING: Your virtualenv is not set up optimally.
    - SUGGESTIONS:
      - Create a virtualenv specifically for Neovim and use `g:python3_host_prog`.  This will avoid the need to install Neovim's Python module in each virtualenv.
  - INFO: Executable: /usr/local/google/home/smwang/.pyenv/versions/neovim3/bin/python
  - INFO: Python3 version: 3.6.5
  - INFO: python-neovim version: 0.2.6
  - SUCCESS: Latest python-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.6p384 (2017-12-14) [x86_64-linux-gnu]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
I can't reproduce this issue on my personal computer. This issue happens only at my work station when I try to edit a file with `.gcl` extension.
However, here's the stack trace:
```
[deoplete] Traceback (most recent call last):
  File "/usr/local/google/home/smwang/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 492, in _on_event
    source.on_event(context)
  File "/usr/local/google/home/smwang/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py", line 34, in on_event
    self._make_cache(context)
  File "/usr/local/google/home/smwang/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py", line 64, in _make_cache
    keyword_pattern),
  File "/usr/local/google/home/smwang/.nvim/bundle/deoplete.nvim/rplugin/python3/deoplete/util.py", line 132, in parse_buffer_pattern
    return list(set(re.compile(pattern).findall('\n'.join(b))))
  File "/usr/local/google/home/smwang/.pyenv/versions/neovim3/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/local/google/home/smwang/.pyenv/versions/neovim3/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/google/home/smwang/.pyenv/versions/neovim3/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/google/home/smwang/.pyenv/versions/neovim3/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/google/home/smwang/.pyenv/versions/neovim3/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/local/google/home/smwang/.pyenv/versions/neovim3/lib/python3.6/sre_parse.py", line 548, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range \w-0 at position 10
Exception during buffer.on_event for event 'BufReadPost': bad character range \w-0 at position 10.  Use :messages / see above for error details.
```

When printing out the pattern in this line
```python
return list(set(re.compile(pattern).findall('\n'.join(b))))
```
I see
```
[a-zA-Z_][\w@0-9_À-ÿ]*
[a-zA-Z_][\w-0-9A-Z_a-z]*
```
I guees my workstation nvim runtime defines some keywords for the gcl filetype that leads to this invalid `\w-0` stuff. I guess the suggestion in this stackoverflow [question](https://stackoverflow.com/questions/28539253/python-regex-bad-character-range) could solve the problem (i.e. moving the `-` in the pattern to the end). However, I don't know how to do that for deoplete. 

## How to reproduce the problem from neovim/Vim startup (Required!)
As stated above, I can't reproduce it if not on my workstation machine.

**Comment by Shougo** [comment]
Please upload `'iskeyword'` value in the buffer.

`:verbose setlocal iskeyword?`

And please upload `:echo deoplete#util#vimoption2python(&l:iskeyword)` result.

**Comment by Shougo** [comment]
It must be reproduce-able in my environment.
Please upload the information.

**Comment by Shougo** [comment]
Fixed.
