### ISSUE TITLE
When loading further sources, deoplete (nvim?) resets the selected entry

### ISSUE THREAD

**Issue by andrewferrier** [Shougo/deoplete.nvim#838]
# Problems summary

When I have multiple sources defined for deoplete, some of which are slow to load (e.g. the dictionary source), and I'm "too quick" for deoplete and select an entry, it resets the selection as soon as further entries are loaded. This is an irritation and means I often end up selecting the wrong one or none at all.

## Expected

deoplete doesn't change the selected entry from the complete list even when lazy-loading more entries from other sources.

## Environment Information

 * deoplete version (SHA1): 75f4dcbf99c16d827c8664399e07b6ae38650acf

 * OS: Darwin Kernel Version 15.5 (OS X 10.11.5) - although it seems to be OS-agnostic.

 * neovim/Vim `:version` output: 
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -W
extra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_
GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180820-18474-5qpt42/neovim-0.3.1/build/config -I/tmp
/neovim-20180820-18474-5qpt42/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180820-18474-5qpt42/neovim
-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180820-18474-5qpt42/neovim-0.3.1/build/include
Compiled by brew@ElCapitan.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.15
  - INFO: python2-neovim version: 0.1.12 (outdated; from /usr/local/lib/python2.7/site-packages/neovim)
  - WARNING: Latest python2-neovim is NOT installed: 0.2.6

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.7.0
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
  - INFO: Host: /Users/ferriera/.gem/bin/neovim-ruby-host
  - WARNING: Gem "neovim" is out-of-date. Installed: 0.3.1, latest: 0.7.0
    - ADVICE:
      - Run in shell: gem update neovim

## Node.js provider (optional)
  - INFO: Node.js: v6.14.3
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.vim/plugged/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('auto_complete_delay', 600)
call deoplete#custom#source('dictionary', 'matchers', ['matcher_head'])

augroup dictionary_init
	autocmd BufRead * setlocal dictionary+=/usr/share/dict/words,~/.vim/spell/en.utf-8.add
augroup END
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Load nvim.
2. Open any file with a number of keywords already in it.
3. Find a blank space and enter insert mode.
4. Enter enough characters to trigger deoplete (e.g. 2). Make sure the characters are a prefix for one of the keywords already in the file (for around/buffer mode), and are also a valid prefix for (unrelated) words in the dictionary.
5. Initially deoplete will just show "around" and "buffer" words. **Quickly** press the down arrow a few times to select one before the "dictionary" words are loaded.
6. Once dictionary words are loaded (approx 0.5 sec on my main system, although slower on some others I have), the selection will be removed from the word you selected.
7. If you "move too fast" and hit Return at this point, no word will be inserted (which is my irritation and the issue here). To work as desired you have to notice that it's been deselected, and reselect it, before hitting Return.

## Generate a logfile if appropriate

```
2018-09-03 15:32:05,483 [ERROR @ base_events.py:default_exception_handler:1591] 38517 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py:1491> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1516, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 924, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2018-09-03 15:32:05,485 [ERROR @ base_events.py:default_exception_handler:1591] 38517 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py:1491> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1516, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 924, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2018-09-03 15:32:05,487 [ERROR @ base_events.py:default_exception_handler:1591] 38517 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py:1491> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1516, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 924, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
2018-09-03 15:32:05,488 [ERROR @ base_events.py:default_exception_handler:1591] 38517 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py:1491> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1516, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 924, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
```

**Comment by Shougo** [comment]
It is not possible.
Because, Vim/neovim does not support the feature.
Closing.

I think you should disable parallel feature.

```vim
       call deoplete#custom#option('num_processes', 1)
```
