### ISSUE TITLE
reference packages cannot be completed

### ISSUE THREAD

**Issue by Marlboro-go** [Shougo/deoplete.nvim#839]
Hi I am a new vimer and github user，my english is not very well. My problem is reference packages cannot be completed, I know it's not proper for me to ask such a question，Please forgive me。I got these errors in log file,

`2018-09-04 19:54:49,026 [ERROR @ base_events.py:default_exception_handler:1591] 2184 - Task exception was never retrieved
future: <Task finished coro=<BaseEventLoop.subprocess_exec() done, defined at /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py:1491> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached')>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1516, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 924, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
`
Like this
![image](https://github.com/Marlboro-go/Error/blob/master/QQ20180904-194624.png)
![qq20180904-194624](https://user-images.githubusercontent.com/41671631/45030519-b000a400-b07e-11e8-8b32-0cfd1c112e52.png)

**Comment by Shougo** [comment]
```
Q: "Cannot add child handler, the child watcher does not have a loop attached"
error.
https://github.com/Shougo/deoplete.nvim/issues/761

A: It is neovim-python package problem.
https://github.com/neovim/python-client/issues/324
https://github.com/neovim/python-client/issues/326

Note: You can disable parallel feature by |deoplete-options-num_processes|.
It is workaround. >

       call deoplete#custom#option('num_processes', 1)

```

**Comment by Marlboro-go** [comment]
I got these in log file 
`2018-09-07 11:26:52,841 [DEBUG @ msgpack_stream.py:send:34] 2543 - sent [0, 1, b'vim_get_api_info', ()]
2018-09-07 11:26:52,841 [DEBUG @ base.py:send:117] 2543 - Sending 'b'\x94\x00\x01\xb0vim_get_api_info\x90''
2018-09-07 11:26:52,841 [DEBUG @ base.py:run:142] 2543 - Entering event loop
2018-09-07 11:26:52,841 [DEBUG @ msgpack_stream.py:_on_data:59] 2543 - waiting for message...
2018-09-07 11:26:52,841 [DEBUG @ msgpack_stream.py:_on_data:61] 2543 - received message: [0, 1, b'poll', []]
2018-09-07 11:26:52,841 [DEBUG @ async_session.py:_on_request:91] 2543 - received request: b'poll', []
2018-09-07 11:26:52,841 [DEBUG @ msgpack_stream.py:_on_data:59] 2543 - waiting for message...
2018-09-07 11:26:52,841 [DEBUG @ msgpack_stream.py:_on_data:64] 2543 - unpacker needs more data...
2018-09-07 11:26:52,842 [DEBUG @ msgpack_stream.py:_on_data:59] 2543 - waiting for message...
2018-09-07 11:26:52,842 [DEBUG @ msgpack_stream.py:_on_data:64] 2543 - unpacker needs more data...
2018-09-07 11:26:52,842 [DEBUG @ msgpack_stream.py:_on_data:59] 2543 - waiting for message...
2018-09-07 11:26:52,843 [DEBUG @ msgpack_stream.py:_on_data:64] 2543 - unpacker needs more data...
2018-09-07 11:26:52,843 [DEBUG @ msgpack_stream.py:_on_data:59] 2543 - waiting for message...`

**Comment by Marlboro-go** [comment]
I reinstall my macos and neovim ,but the reference package complete also cannot use,  These is Ok when I input fmt . ,the deoplete will prompt lot of method ，It's OK。but when i import package ,the method or variable which in the import package , the  deoplete is not ok，It can't prompt these method ,variable and so on.
