### ISSUE TITLE
Error completing c files;w

### ISSUE THREAD

**Issue by binaryplease** [Shougo/deoplete.nvim#859]
# Problems summary

I get an error when editing a c source file
## Expected
display completion or similar

## Environment Information

 * deoplete version (SHA1):

 * OS: Linux arch up-to-date

 * neovim/Vim `:version` output:

```
:version                                                                         
NVIM v0.3.1                                                                      
Build type: Release                                                              
LuaJIT 2.0.5                                                                     
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector
-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedan
tic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -
Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUD
E_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HA
S_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src 
-I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/
include                                                                          
Compiled by builduser                                                            
                                                                                 
Features: +acl +iconv +jemalloc +tui                                             
See ":help feature-compile"                                                      
                                                                                 
   system vimrc file: "$VIM/sysinit.vim"                                         
  fall-back for $VIM: "/usr/share/nvim"                                          
                                                                                 
# Run :checkhealth for more info 
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: General viewer should work properly!
  - WARNING: Compiler callbacks will not work!
    - ADVICE:
      - `neovim-remote` / `nvr` is required for callbacks to work with neovim
      - Please also set |g:vimtex_compiler_progname| = 'nvr'
      - For more info, see :help |vimtex-faq-neovim|

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - WARNING: $NVIM_TUI_ENABLE_CURSOR_SHAPE is ignored in Nvim 0.2+
    - ADVICE:
      - Use the 'guicursor' option to configure cursor shape. :help |'guicursor'|
      - https://github.com/neovim/neovim/wiki/Following-HEAD#20170402

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5002'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.15
  - INFO: python2-neovim version: 0.2.6
  - OK: Latest python2-neovim is installed: 0.2.6

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.7.0
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
  - INFO: Host: /usr/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.7.1

## Node.js provider (optional)
  - INFO: Node.js: v10.11.0
  - INFO: Neovim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.2.1


```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
https://ptpb.pw/PlYc
All dotfiles at github.com/binaryplease/dotfiles I cant reproduce the issue with the example vimrc

## How to reproduce the problem from neovim/Vim startup (Required!)

1. open a file containing:
```
/* Hello World program */
#include <stdio.h>
main()
{
    printf("Hello World");
	return 0;
}
```

2. put cursor on the m of "main".
3. Press capital i (I) 
4. Start typing the word "int"

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/1719781/46947165-3fd03f80-d07a-11e8-8a65-bac05e2f757e.png)

## Upload the log file
output of :messages
```
[deoplete] Traceback (most recent call last):                                                                                                                             
  File "/home/binaryplease/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 220, in _gather_results                                                    
    ctx['candidates'] = source.gather_candidates(ctx)                                                                                                                     
  File "/home/binaryplease/.vim/plugged/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 163, in gather_candidates                                
    params, refresh)                                                                                                                                                      
  File "/home/binaryplease/.vim/plugged/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 335, in get_completion                                   
    tu = self.get_translation_unit(fname, args, buf)                                                                                                                      
  File "/home/binaryplease/.vim/plugged/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 319, in get_translation_unit                             
    tu.reparse(buf)                                                                                                                                                       
  File "/usr/lib/python3.7/site-packages/clang/cindex.py", line 2980, in reparse                                                                                          
    unsaved_files_array[i].name = name                                                                                                                                    
TypeError: bytes or integer address expected instead of str instance                                                                                                      
Error from clang: TypeError('bytes or integer address expected instead of str instance').  Use :messages / see above for error details.                                   
[deoplete] Traceback (most recent call last):                                                                                                                             
  File "/home/binaryplease/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 220, in _gather_results                                                    
    ctx['candidates'] = source.gather_candidates(ctx)                                                                                                                     
  File "/home/binaryplease/.vim/plugged/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 163, in gather_candidates                                
    params, refresh)                                                                                                                                                      
  File "/home/binaryplease/.vim/plugged/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 335, in get_completion                                   
    tu = self.get_translation_unit(fname, args, buf)                                                                                                                      
  File "/home/binaryplease/.vim/plugged/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 319, in get_translation_unit                             
    tu.reparse(buf)                                                                                                                                                       
  File "/usr/lib/python3.7/site-packages/clang/cindex.py", line 2980, in reparse                                                                                          
    unsaved_files_array[i].name = name                                                                                                                                    
TypeError: bytes or integer address expected instead of str instance                                                                                                      
Error from clang: TypeError('bytes or integer address expected instead of str instance').  Use :messages / see above for error details.                                   
[deoplete] Too many errors from "clang". This source is disabled until Neovim is restarted.  
```

**Comment by Shougo** [comment]
deoplete-clang is not maintained.
I recommend for you to use deoplete-clangx instead.
https://github.com/Shougo/deoplete-clangx

**Comment by binaryplease** [comment]
I see, thank you!

**Comment by binaryplease** [comment]
@Shougo You might want to change it here too: https://github.com/Shougo/deoplete.nvim/wiki/Completion-Sources

**Comment by Shougo** [comment]
You can do it.

**Comment by binaryplease** [comment]
Done.
