### ISSUE TITLE
Incompatibility with pynvim 0.3.1?

### ISSUE THREAD

**Issue by rubdos** [Shougo/deoplete.nvim#884]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Deoplete works as expected on `.vimrc` and other vim scripts. However, when opening Rust, Java or TeX files, deoplete seems to fail. This is combined with LanguageClient-neovim, which is confirmed working via `C-X C-O`.When triggering a completion, nvim backend fails on a UTF-8 error:

```
Traceback (most recent call last):
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_server.py", line 400, in process_pending_requests
    packed = msgpack.packb(neovim_rpc_protocol.to_client(result))
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 66, in to_client
    return walk(handler, msg)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 20, in walk
    return list(walk(fn, o) for o in obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 20, in <genexpr>
    return list(walk(fn, o) for o in obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 23, in walk
    obj.items())
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 22, in <genexpr>
    return dict((walk(fn, k), walk(fn, v)) for k, v in
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 20, in walk
    return list(walk(fn, o) for o in obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 20, in <genexpr>
    return list(walk(fn, o) for o in obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 24, in walk
    return fn(obj)
  File "/usr/share/vim/vimfiles/pythonx/neovim_rpc_protocol.py", line 64, in handler
    return obj.name
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

When digging deeper, it seems to be that this is triggered in `rplugin/python3/deoplete/context.py`, when 

```python
            'keyword_pattern': self._vim.call(
                'deoplete#util#get_keyword_pattern', filetype),
```

is called, but I am not sure. It seems like everything before that call got handled correctly.

## Expected

Deoplete should offer completions on any configured language.

## Environment Information

 * deoplete version (SHA1): acae373

 * OS: Arch Linux

 * neovim/Vim `:version` output: `VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 22 2018 19:40:14)`

 * `python-neovim`: 0.3.1.r14.g3efa487-1, `python-msgpack`: 0.5.6-2, `python-greenlet`: 0.4.15-1

 * `:checkhealth` or `:CheckHealth` result(neovim only): n/a

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let g:deoplete#enable_at_startup = 1
```

I have `deoplete`, `yarp` and `vim-hug-neovim-rpc` installed on the system (`/usr/lib/vim/vimfiles/`), but it did not make a difference to have them separate.

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. install `python-neovim-git` (which is version 0.3.1)

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. vim -u minimal.vimrc
 4. trigger a completion
 5. cat /tmp/log_{PID}

## Screenshot (if possible)

n/a, doesn't show errors, doesn't show completions.

## Upload the log file

[nvim_log_py3_neovim_rpc_server.log](https://github.com/Shougo/deoplete.nvim/files/2633264/nvim_log_py3_neovim_rpc_server.log)

**Comment by rubdos** [comment]
I was wrong.

The issue seems to be 100% in neovim-client: serialisation of `vim.Function` objects seems to fail. I'm closing this in favour of the issue I'll open in a second on pynvim.
