### ISSUE TITLE
Unused stdout causes Error

### ISSUE THREAD

**Issue by e-kwsm** [Shougo/deoplete.nvim#899]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
If `stdout` in a source is not used (not piped), error occurs:
```
[deoplete] Traceback (most recent call last):
  File "/tmp/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 81, in completion_begin
    is_async, position, candidates = self._merge_results(context)
  File "/tmp/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 161, in _merge_results
    [is_async, results] = self._get_results(context)
  File "/tmp/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 144, in _get_results
    result = parent.merge_results(context)
  File "/tmp/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 110, in merge_results
    get = self._get(queue_id)
  File "/tmp/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 148, in _get
    return [x for x in outs if x['queue_id'] == queue_id]
  File "/tmp/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 148, in <listcomp>
    return [x for x in outs if x['queue_id'] == queue_id]
TypeError: 'int' object is not subscriptable
Error while gathering completions.  Use :messages / see above for error details.
```

The problem is that the above message is not so intuitive as to find the cause.

## Expected
No error occurs.

## Environment Information

 * deoplete version (SHA1): dc745e2a97025310c5439d304b5a8486550384bc

 * OS: Debian 9.5

 * neovim/Vim `:version` output: `NVIM v0.3.2-dev`

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='4601'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the pynvim module.  Using the first available for diagnostics.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "pynvim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "pynvim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "pynvim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.5.3
  - INFO: pynvim version: 0.3.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.5+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath-=~/.config/nvim
set runtimepath-=~/.config/nvim/after
set runtimepath+=/tmp/deoplete.nvim
set runtimepath+=/tmp/rtp

let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

```shellsession
$ cd /tmp
$ git clone --depth 1 https://github.com/Shougo/deoplete.nvim
$ mkdir -p /tmp/rtp/rplugin/python3/deoplete/source
$ cat << EOF > /tmp/rtp/rplugin/python3/deoplete/source/unused-stdout.py
import subprocess
from .base import Base


class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name = "unused-stdout"
        subprocess.run(["echo"],
                       #stdout=subprocess.DEVNULL
                       )

    def gather_candidates(self, context):
        return []
EOF
```

Then `nvim -u vimrc` and enter insert mode.

If stdout is piped or dumped into `DEVNULL`, the error does not occur. OTOH, uncaptured stderr does not cause error.
I guess unused stdout affects `rplugin/python3/deoplete/child.py` or `rplugin/python3/deoplete/dp_main.py`.

**Comment by Shougo** [comment]
Unfortunately, it is the feature of deoplete.

The original stdout is used for MessagePack communication.
You must disable stdout.

Note: `sys.stdout` is already disabled.  But subprocess uses other method to get stdout.

If you can fix it in deoplete side, please create the PR.
