### ISSUE TITLE
Error occured in Vim8

### ISSUE THREAD

**Issue by jshin** [Shougo/deoplete.nvim#926]
# Problems summary
When deoplete.nvim is loaded in Vim, the following messages are displayed.
(The name of a home directory has been renamed to "~/".)
```text
[deoplete@yarp] error caught in notification handler 'deoplete_on_event [{'rpc': 'deoplete_on_event', 'event': 'InsertEnter', 'sources': []}]'
[deoplete@yarp] Traceback (most recent call last):
[deoplete@yarp]   File "~/tmp/plugins/.cache/minimal.vimrc/.dein/pythonx/yarp.py", line 36, in on_notification
[deoplete@yarp]     getattr(module_obj, method)(*args)
[deoplete@yarp]   File "~/tmp/plugins/.cache/minimal.vimrc/.dein/rplugin/python3/deoplete/__init__.py", line 67, in deoplete_on_event
[deoplete@yarp]     global_deoplete.on_event(context)
[deoplete@yarp]   File "~/tmp/plugins/.cache/minimal.vimrc/.dein/rplugin/python3/deoplete/deoplete.py", line 126, in on_event
[deoplete@yarp]     self.init_context()
[deoplete@yarp]   File "~/tmp/plugins/.cache/minimal.vimrc/.dein/rplugin/python3/deoplete/deoplete.py", line 58, in init_context
[deoplete@yarp]     self._context = Context(self._vim)
[deoplete@yarp]   File "~/tmp/plugins/.cache/minimal.vimrc/.dein/rplugin/python3/deoplete/context.py", line 15, in __init__
[deoplete@yarp]     self._prev_filetype = self._vim.options['filetype']
[deoplete@yarp]   File "~/Library/Python/3.7/lib/python/site-packages/pynvim/api/common.py", line 88, in __getitem__
[deoplete@yarp]     return self._get(key)
[deoplete@yarp]   File "~/Library/Python/3.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
[deoplete@yarp]     res = self._session.request(name, *args, **kwargs)
[deoplete@yarp]   File "~/Library/Python/3.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
[deoplete@yarp]     raise self.error_wrapper(err)
[deoplete@yarp] pynvim.api.nvim.NvimError: b"'filetype'"
```

## Expected
Committed by d228567ce79e071d84f4e45811193de789c1c246.

## Environment Information

 * deoplete version (SHA1): d228567ce79e071d84f4e45811193de789c1c246

 * OS: macOS 10.12.6

 * Python3: Python 3.7.0

 * neovim/Vim `:version` output:
```text

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 31 2019 16:44:35)
macOS 版
適用済パッチ: 1-850
Compiled by Homebrew
Huge 版 without GUI.  機能の一覧 有効(+)/無効(-)
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              -mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
      システム vimrc: "$VIM/vimrc"
      ユーザー vimrc: "$HOME/.vimrc"
   第2ユーザー vimrc: "~/.vim/vimrc"
       ユーザー exrc: "$HOME/.exrc"
  デフォルトファイル: "$VIMRUNTIME/defaults.vim"
       省略時の $VIM: "/usr/local/share/vim"
コンパイル: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
リンク: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6     
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/tmp/plugins/repos/github.com/Shougo/dein.vim
if dein#load_state('~/tmp/plugins/')
    call dein#begin('~/tmp/plugins')
    call dein#add('Shougo/dein.vim')
    call dein#add('Shougo/deoplete.nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
endif

let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. `mkdir -p ~/tmp/plugins && cd ~/tmp/plugins`
 2. `git curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh && sh ./installer.sh .`
 3. `vim -N -u ~/tmp/vimrc -i NONE`
 4. When the mode is changed InsertMode, error messages are displayed.

**Comment by Collin-Moore** [comment]
I also have this problem, I'm running on Ubuntu 18.04.

Here are some logs I have

**nvim_log_py3_deoplete**
```
2019-02-02 16:15:38,472 [DEBUG @ session.py:handler:223] 31607 - greenlet <greenlet.greenlet object at 0x7f23f9d2db90> is now dying...
2019-02-02 16:15:38,472 [DEBUG @ msgpack_stream.py:_on_data:58] 31607 - waiting for message...
2019-02-02 16:15:38,472 [DEBUG @ msgpack_stream.py:_on_data:63] 31607 - unpacker needs more data...
2019-02-02 16:15:38,610 [DEBUG @ msgpack_stream.py:_on_data:58] 31607 - waiting for message...
2019-02-02 16:15:38,610 [DEBUG @ msgpack_stream.py:_on_data:60] 31607 - received message: [2, b'deoplete_auto_completion_begin', [{b'rpc': b'deoplete_auto_completion_begin', b'event': b'TextChangedI'}]]
2019-02-02 16:15:38,611 [DEBUG @ async_session.py:_on_notification:107] 31607 - received notification: b'deoplete_auto_completion_begin', [{b'rpc': b'deoplete_auto_completion_begin', b'event': b'TextChangedI'}]
2019-02-02 16:15:38,611 [DEBUG @ session.py:_on_notification:226] 31607 - received rpc notification, greenlet <greenlet.greenlet object at 0x7f23f9d2db90> will handle it
2019-02-02 16:15:38,611 [DEBUG @ msgpack_stream.py:send:33] 31607 - sent [0, 15, 'nvim_get_option', ('filetype',)]
2019-02-02 16:15:38,611 [DEBUG @ base.py:send:117] 31607 - Sending 'b'\x94\x00\x0f\xafnvim_get_option\x91\xa8filetype''
2019-02-02 16:15:38,611 [DEBUG @ session.py:_yielding_request:163] 31607 - yielding from greenlet <greenlet.greenlet object at 0x7f23f9d2db90> to wait for response
2019-02-02 16:15:38,611 [DEBUG @ msgpack_stream.py:_on_data:58] 31607 - waiting for message...
2019-02-02 16:15:38,611 [DEBUG @ msgpack_stream.py:_on_data:63] 31607 - unpacker needs more data...
2019-02-02 16:15:38,613 [DEBUG @ msgpack_stream.py:_on_data:58] 31607 - waiting for message...
2019-02-02 16:15:38,613 [DEBUG @ msgpack_stream.py:_on_data:60] 31607 - received message: [1, 15, [1, b"'filetype'"], None]
2019-02-02 16:15:38,613 [DEBUG @ async_session.py:_on_response:100] 31607 - received response: [1, b"'filetype'"], None
2019-02-02 16:15:38,613 [DEBUG @ session.py:response_cb:159] 31607 - response is available for greenlet <greenlet.greenlet object at 0x7f23f9d2db90>, switching back
2019-02-02 16:15:38,613 [INFO @ session.py:request:101] 31607 - 'Received error: [1, b"'filetype'"]
2019-02-02 16:15:38,614 [WARNING @ session.py:handler:221] 31607 - error caught while processing notification 'b'deoplete_auto_completion_begin' [{b'rpc': b'deoplete_auto_completion_begin', b'event': b'TextChangedI'}]': Traceback (most recent call last):
  File "/home/collin/.local/lib/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 217, in handler
    self._notification_cb(name, args)
  File "/home/collin/.local/lib/python3.6/site-packages/pynvim/api/nvim.py", line 222, in filter_notification_cb
    notification_cb(name, args)
  File "/home/collin/.vim/bundle/nvim-yarp/pythonx/yarp.py", line 36, in on_notification
    getattr(module_obj, method)(*args)
  File "/home/collin/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 61, in deoplete_auto_completion_begin
    global_deoplete.completion_begin(context)
  File "/home/collin/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 67, in completion_begin
    self.init_context()
  File "/home/collin/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 58, in init_context
    self._context = Context(self._vim)
  File "/home/collin/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/context.py", line 15, in __init__
    self._prev_filetype = self._vim.options['filetype']
  File "/home/collin/.local/lib/python3.6/site-packages/pynvim/api/common.py", line 88, in __getitem__
    return self._get(key)
  File "/home/collin/.local/lib/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/collin/.local/lib/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b"'filetype'"
```

**nvim_log_py3_neovim_rpc_server**
```
2019-02-02 16:15:36,451 [INFO @ neovim_rpc_server.py:process_pending_requests:399] 31603 - sending result: [1, 13, [1, "'filetype'"], None]
2019-02-02 16:15:36,451 [INFO @ neovim_rpc_server.py:process_pending_requests:402] 31603 - sent
2019-02-02 16:15:36,452 [INFO @ neovim_rpc_server.py:process_pending_requests:359] 31603 - process_pending_requests
2019-02-02 16:15:38,469 [INFO @ neovim_rpc_server.py:notify:225] 31603 - notify channel[1]: [2, b'deoplete_auto_completion_begin', <vim.list object at 0x7f858d02d750>]
2019-02-02 16:15:38,470 [INFO @ neovim_rpc_server.py:handle:170] 31603 - unpacked: [0, 14, b'nvim_get_option', [b'filetype']]
2019-02-02 16:15:38,470 [INFO @ neovim_rpc_server.py:notify:68] 31603 - sending notification: ["ex", "pythonx neovim_rpc_server.process_pending_requests()"]
2019-02-02 16:15:38,470 [INFO @ neovim_rpc_server.py:process_pending_requests:359] 31603 - process_pending_requests
2019-02-02 16:15:38,471 [INFO @ neovim_rpc_server.py:process_pending_requests:371] 31603 - get msg from channel [1]: [0, 14, 'nvim_get_option', ['filetype']]
2019-02-02 16:15:38,471 [ERROR @ neovim_rpc_server.py:process_pending_requests:393] 31603 - process failed: 'filetype'
Traceback (most recent call last):
  File "/home/collin/.vim/bundle/vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py", line 391, in process_pending_requests
    result = _process_request(channel, method, args)
  File "/home/collin/.vim/bundle/vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py", line 426, in _process_request
    return getattr(neovim_rpc_methods, method)(*args)
  File "/home/collin/.vim/bundle/vim-hug-neovim-rpc/pythonx/neovim_rpc_methods.py", line 83, in nvim_get_option
    return vim.options[name]
KeyError: 'filetype'
2019-02-02 16:15:38,471 [INFO @ neovim_rpc_server.py:process_pending_requests:399] 31603 - sending result: [1, 14, [1, "'filetype'"], None]
2019-02-02 16:15:38,471 [INFO @ neovim_rpc_server.py:process_pending_requests:402] 31603 - sent
2019-02-02 16:15:38,610 [INFO @ neovim_rpc_server.py:notify:225] 31603 - notify channel[1]: [2, b'deoplete_auto_completion_begin', <vim.list object at 0x7f858d02de10>]
2019-02-02 16:15:38,611 [INFO @ neovim_rpc_server.py:handle:170] 31603 - unpacked: [0, 15, b'nvim_get_option', [b'filetype']]
2019-02-02 16:15:38,611 [INFO @ neovim_rpc_server.py:notify:68] 31603 - sending notification: ["ex", "pythonx neovim_rpc_server.process_pending_requests()"]
2019-02-02 16:15:38,612 [INFO @ neovim_rpc_server.py:process_pending_requests:359] 31603 - process_pending_requests
2019-02-02 16:15:38,612 [INFO @ neovim_rpc_server.py:process_pending_requests:371] 31603 - get msg from channel [1]: [0, 15, 'nvim_get_option', ['filetype']]
2019-02-02 16:15:38,612 [ERROR @ neovim_rpc_server.py:process_pending_requests:393] 31603 - process failed: 'filetype'
Traceback (most recent call last):
  File "/home/collin/.vim/bundle/vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py", line 391, in process_pending_requests
    result = _process_request(channel, method, args)
  File "/home/collin/.vim/bundle/vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py", line 426, in _process_request
    return getattr(neovim_rpc_methods, method)(*args)
  File "/home/collin/.vim/bundle/vim-hug-neovim-rpc/pythonx/neovim_rpc_methods.py", line 83, in nvim_get_option
    return vim.options[name]
KeyError: 'filetype'
```

**Comment by roxma** [comment]
`self._vim.options['filetype']` doesn't seem to be valid.

`:help python-options`

> You cannot use this object to obtain or set local options' values or access
> local-only options in any fashion. Raises KeyError if no global option with
> such name exists

I don't know why it doesn't raise error on neovim. But `vim.options['filetype']` should be considered invalid since `filetype` is not global option.

An alternative is to use `vim.current.buffer.options['filetype']`. Personally I don't like it, this envolves at least two rpc traffic on neovim, one for `current.buffer`, then `buffer.options`.
