### ISSUE TITLE
Error with Elixir omni-completion

### ISSUE THREAD

**Issue by archSeer** [Shougo/deoplete.nvim#98]
There is a elixir.vim fork that uses an Elixir host to provide autocompletion. The reference is here: https://github.com/awetzel/neovim-elixir The actual user library is here: https://github.com/awetzel/vim-elixir/tree/nvim-rplugin

I set it up and told deoplete to use omni completion for suggestions:
```vim
" ...
Plug 'awetzel/vim-elixir', {'branch': 'nvim-rplugin'}
" ...

let g:echodoc_enable_at_startup = 1
if has('nvim')
  " Use deoplete.
  let g:deoplete#enable_at_startup = 1
  " Use smartcase.
  let g:deoplete#enable_smart_case = 1

  let g:deoplete#sources = {}
  "let g:deoplete#sources._ = ['buffer', 'tag']
  let g:deoplete#sources.elixir = ['omni']

  " <C-h>, <BS>: close popup and delete backword char.
  inoremap <expr><C-h> deoplete#mappings#smart_close_popup()."\<C-h>"
  inoremap <expr><BS> deoplete#mappings#smart_close_popup()."\<C-h>"

  " <CR>: close popup and save indent.
  inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
  function! s:my_cr_function()
    return deoplete#mappings#close_popup() . "\<CR>"
  endfunction

  let g:deoplete#omni#input_patterns = {}
  let g:deoplete#omni#input_patterns.ruby =
        \ ['[^. *\t]\.\w*', '[a-zA-Z_]\w*::']
  let g:deoplete#omni#input_patterns.elixir =
        \ ['[^. *\t]\.\w*', '[a-zA-Z_]\w*::']
endif
```

I installed the plugin and ran `:UpdateRemotePlugins` to enable the Elixir host. It works fine if I disable deoplete and use <C-x><C-o>. 

The syntax is similar to ruby, so I copied the same regex. I enabled deoplete tried to type `Enum.e` and got this error:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/speed/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 49, in completion_begin
[deoplete]     context)
[deoplete]   File "/Users/speed/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 97, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/speed/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 118, in gather_results
[deoplete]     if charpos >= 0 and source.is_bytepos:
[deoplete] TypeError: unorderable types: list() >= int()
[deoplete] An error has occurred. Please execute :messages command.
```

**Comment by archSeer** [comment]
I figured it out! The omnicomplete function was broken, it looked for `ElixirComplete("1", "")` instead of `ElixirComplete(1, "")`. I created a deoplete plugin that I will release later today.

**Comment by Shougo** [comment]
OK
