### ISSUE TITLE
Failed to run :UpdateRemotePlugins

### ISSUE THREAD

**Issue by fuweid** [Shougo/deoplete.nvim#986]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Failed to run `:UpdateRemotePlugins` 

```
Encountered SyntaxError loading plugin at /home/fuweid/deoplete.nvim/rplugin/python3/deoplete: invalid syntax (process.py, line 23)                                                   
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pynvim/plugin/host.py", line 145, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/fuweid/deoplete.nvim/rplugin/python3/deoplete/process.py", line 23
    self._plugin._queue_err.put(f'stderr from child process:{data}')
                                                                  ^
SyntaxError: invalid syntax
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/fuweid/.local/share/nvim/rplugin.vim
```

It seems the error is related to python syntax. 

## Expected

No error.

## Environment Information

 * deoplete version (SHA1): aebaec4adbb65339601063f1ee533eef09220145

 * OS:

```
Linux debian 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
```

 * neovim/Vim `:version` output:

```
 v0.4.0-1159-g35b959c60
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wcon
version -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI
_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/incl
ude -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-3cea8125-3f9d-4f76-8cde-177dad31efaf

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - ERROR: Python3.6.1+ was not successful
    - ADVICE:
      - Please use Python3.6.1+.
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: "deoplete.nvim" is not registered.
  - WARNING: Out of date
    - ADVICE:
      - Run `:UpdateRemotePlugins`

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. 'termguicolors' won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: tmux

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help provider-python
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.5.3
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help g:ruby_host_prog for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()
```

NOTE: When I use the following the init.vim with commit 5.0 tag, it works.

```
call plug#begin('~/.vim/plugged')

Plug 'Shougo/deoplete.nvim', { 'tag': '5.0', 'do': ':UpdateRemotePlugins' }

call plug#end()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. :PlugInstall
 2. :UpdateRemotePlugins

**Comment by fuweid** [comment]
`ERROR: Python3.6.1+ was not successful` 

It seems the python version is lower than required one. Feel frustrated about the syntax...

**Comment by Shougo** [comment]
Yes.  Your Python 3.5 is old to use deoplete.

**Comment by markstos** [comment]
Could we have a nice error that says "Your python is too old" with the minimum supported version printed, instead of the stacktrace we have now?  I'm trying to use this on Chrome OS which is still officially supporting only a Debian Stretch environment which is shipping Python 3.5.

**Comment by Shougo** [comment]
Sorry.  It is not possible.
:checkhealth prints more nice error messages.
